"""add_category

Revision ID: 1665fff6b24e
Revises: 38733a0fdc78
Create Date: 2026-02-21 12:24:24.264750

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1665fff6b24e"
down_revision: str | Sequence[str] | None = "38733a0fdc78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
