"""add_category_to_classifieds

Revision ID: 38733a0fdc78
Revises: 1633984704a7
Create Date: 2026-02-21 12:21:32.029102

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38733a0fdc78"
down_revision: str | Sequence[str] | None = "1633984704a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("classifieds", sa.Column("category", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classifieds", "category")
    # ### end Alembic commands ###
