"""pluralize_session_days

Revision ID: 50ffd2469863
Revises: 0030e88286c3
Create Date: 2026-02-19 10:16:00.129153

"""
from typing import Sequence, Union

from alembic import op
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ffd2469863'
down_revision: Union[str, Sequence[str], None] = '0030e88286c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Alter column to VARCHAR(50) so we can update values without Enum constraints
    op.alter_column('lodges', 'session_day',
               existing_type=sa.String(length=50),
               type_=sa.String(50),
               existing_nullable=True)

    # 2. Update existing values to plural
    op.execute("UPDATE lodges SET session_day = 'Domingos' WHERE session_day = 'Domingo'")
    op.execute("UPDATE lodges SET session_day = 'Segundas-feiras' WHERE session_day = 'Segunda-feira'")
    op.execute("UPDATE lodges SET session_day = 'Terças-feiras' WHERE session_day = 'Terça-feira'")
    op.execute("UPDATE lodges SET session_day = 'Quartas-feiras' WHERE session_day = 'Quarta-feira'")
    op.execute("UPDATE lodges SET session_day = 'Quintas-feiras' WHERE session_day = 'Quinta-feira'")
    op.execute("UPDATE lodges SET session_day = 'Sextas-feiras' WHERE session_day = 'Sexta-feira'")
    op.execute("UPDATE lodges SET session_day = 'Sábados' WHERE session_day = 'Sábado'")

    # 3. Alter column to new Enum type
    op.alter_column('lodges', 'session_day',
               existing_type=sa.String(50),
               type_=sa.Enum('Domingos', 'Segundas-feiras', 'Terças-feiras', 'Quartas-feiras', 'Quintas-feiras', 'Sextas-feiras', 'Sábados', name='session_day_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lodges', 'session_day',
               existing_type=sa.Enum('Domingos', 'Segundas-feiras', 'Terças-feiras', 'Quartas-feiras', 'Quintas-feiras', 'Sextas-feiras', 'Sábados', name='session_day_enum'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
