"""Add state value to members table

Revision ID: 8ac9f1f9dded
Revises: ab3b3f1e3525
Create Date: 2026-01-21 10:27:53.627525

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ac9f1f9dded"
down_revision: str | Sequence[str] | None = "ab3b3f1e3525"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("members", sa.Column("state", sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "state")
    # ### end Alembic commands ###
