"""Initial sync

Revision ID: ab3b3f1e3525
Revises:
Create Date: 2026-01-20 09:06:51.055054

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ab3b3f1e3525"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
