"""Add subobedience_id to Lodge

Revision ID: ba500e34986d
Revises: 50ffd2469863
Create Date: 2026-02-20 10:20:28.298323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba500e34986d'
down_revision: Union[str, Sequence[str], None] = '50ffd2469863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('subobedience_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lodges', 'obediences', ['subobedience_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lodges', type_='foreignkey')
    op.drop_column('lodges', 'subobedience_id')
    # ### end Alembic commands ###
