"""Add financial module models

Revision ID: d850e1e705ac
Revises: 1665fff6b24e
Create Date: 2026-02-22 12:04:05.740093

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d850e1e705ac"
down_revision: str | Sequence[str] | None = "1665fff6b24e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_financial_categories_id"), "financial_categories", ["id"], unique=False)
    op.create_index(op.f("ix_financial_categories_lodge_id"), "financial_categories", ["lodge_id"], unique=False)
    op.create_table(
        "lodge_financial_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("active_gateway", sa.String(length=50), nullable=False),
        sa.Column("gateway_api_key", sa.String(length=255), nullable=True),
        sa.Column("gateway_webhook_secret", sa.String(length=255), nullable=True),
        sa.Column("strict_budget_control", sa.Boolean(), nullable=True),
        sa.Column("recalculate_late_fees", sa.Boolean(), nullable=True),
        sa.Column("default_penalty_percent", sa.Float(), nullable=True),
        sa.Column("default_interest_percent", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lodge_financial_configs_id"), "lodge_financial_configs", ["id"], unique=False)
    op.create_index(op.f("ix_lodge_financial_configs_lodge_id"), "lodge_financial_configs", ["lodge_id"], unique=True)
    op.create_table(
        "annual_budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("budgeted_amount", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["financial_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_annual_budgets_category_id"), "annual_budgets", ["category_id"], unique=False)
    op.create_index(op.f("ix_annual_budgets_id"), "annual_budgets", ["id"], unique=False)
    op.create_index(op.f("ix_annual_budgets_lodge_id"), "annual_budgets", ["lodge_id"], unique=False)
    op.add_column("financial_transactions", sa.Column("category_id", sa.Integer(), nullable=True))
    op.add_column("financial_transactions", sa.Column("status", sa.String(length=50), nullable=False))
    op.add_column("financial_transactions", sa.Column("due_date", sa.Date(), nullable=False))
    op.add_column("financial_transactions", sa.Column("payment_date", sa.Date(), nullable=True))
    op.add_column("financial_transactions", sa.Column("competency_date", sa.Date(), nullable=False))
    op.add_column("financial_transactions", sa.Column("original_amount", sa.Float(), nullable=False))
    op.add_column("financial_transactions", sa.Column("interest_amount", sa.Float(), nullable=True))
    op.add_column("financial_transactions", sa.Column("penalty_amount", sa.Float(), nullable=True))
    op.add_column("financial_transactions", sa.Column("discount_amount", sa.Float(), nullable=True))
    op.add_column("financial_transactions", sa.Column("paid_amount", sa.Float(), nullable=True))
    op.add_column("financial_transactions", sa.Column("gateway_id", sa.String(length=100), nullable=True))
    op.add_column("financial_transactions", sa.Column("gateway_link", sa.String(length=255), nullable=True))
    op.add_column("financial_transactions", sa.Column("gateway_barcode", sa.String(length=255), nullable=True))
    op.add_column("financial_transactions", sa.Column("gateway_pix_qrcode", sa.Text(), nullable=True))
    op.add_column("financial_transactions", sa.Column("gateway_status", sa.String(length=100), nullable=True))
    op.alter_column("financial_transactions", "member_id", existing_type=sa.Integer(), nullable=True)
    op.alter_column(
        "financial_transactions", "description", existing_type=sa.Text(), type_=sa.String(length=255), nullable=False
    )
    op.create_index(
        op.f("ix_financial_transactions_category_id"), "financial_transactions", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_financial_transactions_member_id"), "financial_transactions", ["member_id"], unique=False)
    op.create_foreign_key(None, "financial_transactions", "financial_categories", ["category_id"], ["id"])
    op.drop_column("financial_transactions", "amount")
    op.drop_column("financial_transactions", "transaction_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "financial_transactions",
        sa.Column("transaction_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
    )
    op.add_column("financial_transactions", sa.Column("amount", sa.Float(), nullable=False))
    op.drop_constraint(None, "financial_transactions", type_="foreignkey")
    op.drop_index(op.f("ix_financial_transactions_member_id"), table_name="financial_transactions")
    op.drop_index(op.f("ix_financial_transactions_category_id"), table_name="financial_transactions")
    op.alter_column(
        "financial_transactions", "description", existing_type=sa.String(length=255), type_=sa.Text(), nullable=True
    )
    op.alter_column("financial_transactions", "member_id", existing_type=sa.Integer(), nullable=False)
    op.drop_column("financial_transactions", "gateway_status")
    op.drop_column("financial_transactions", "gateway_pix_qrcode")
    op.drop_column("financial_transactions", "gateway_barcode")
    op.drop_column("financial_transactions", "gateway_link")
    op.drop_column("financial_transactions", "gateway_id")
    op.drop_column("financial_transactions", "paid_amount")
    op.drop_column("financial_transactions", "discount_amount")
    op.drop_column("financial_transactions", "penalty_amount")
    op.drop_column("financial_transactions", "interest_amount")
    op.drop_column("financial_transactions", "original_amount")
    op.drop_column("financial_transactions", "competency_date")
    op.drop_column("financial_transactions", "payment_date")
    op.drop_column("financial_transactions", "due_date")
    op.drop_column("financial_transactions", "status")
    op.drop_column("financial_transactions", "category_id")
    op.drop_index(op.f("ix_annual_budgets_lodge_id"), table_name="annual_budgets")
    op.drop_index(op.f("ix_annual_budgets_id"), table_name="annual_budgets")
    op.drop_index(op.f("ix_annual_budgets_category_id"), table_name="annual_budgets")
    op.drop_table("annual_budgets")
    op.drop_index(op.f("ix_lodge_financial_configs_lodge_id"), table_name="lodge_financial_configs")
    op.drop_index(op.f("ix_lodge_financial_configs_id"), table_name="lodge_financial_configs")
    op.drop_table("lodge_financial_configs")
    op.drop_index(op.f("ix_financial_categories_lodge_id"), table_name="financial_categories")
    op.drop_index(op.f("ix_financial_categories_id"), table_name="financial_categories")
    op.drop_table("financial_categories")
    # ### end Alembic commands ###
