"""Add installation_date to Member model

Revision ID: 0030e88286c3
Revises: 8ac9f1f9dded
Create Date: 2026-02-18 13:04:00.589622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0030e88286c3'
down_revision: Union[str, Sequence[str], None] = '8ac9f1f9dded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('installation_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'installation_date')
    # ### end Alembic commands ###
