'''Add dashboard models

Revision ID: 10426a5c3186
Revises: fe6c2cf21501
Create Date: 2025-11-29 12:15:13.579831

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10426a5c3186'
down_revision = 'fe6c2cf21501'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifieds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifieds_id'), 'classifieds', ['id'], unique=False)
    op.create_index(op.f('ix_classifieds_lodge_id'), 'classifieds', ['lodge_id'], unique=False)
    op.create_table('dining_scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dining_scales_id'), 'dining_scales', ['id'], unique=False)
    op.create_index(op.f('ix_dining_scales_lodge_id'), 'dining_scales', ['lodge_id'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    op.create_index(op.f('ix_notices_lodge_id'), 'notices', ['lodge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_lodge_id'), table_name='notices')
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_dining_scales_lodge_id'), table_name='dining_scales')
    op.drop_index(op.f('ix_dining_scales_id'), table_name='dining_scales')
    op.drop_table('dining_scales')
    op.drop_index(op.f('ix_classifieds_lodge_id'), table_name='classifieds')
    op.drop_index(op.f('ix_classifieds_id'), table_name='classifieds')
    op.drop_table('classifieds')
    # ### end Alembic commands ###
