'''Add Titles and Signatures Config

Revision ID: 10bbc71f88aa
Revises: 32c483878082
Create Date: 2025-12-14 11:57:18.716519

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10bbc71f88aa'
down_revision = '32c483878082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
