"""Add member json and static fields

Revision ID: 1269c4b09e73
Revises: 93890040ddd7
Create Date: 2026-07-22 09:42:08.653878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1269c4b09e73'
down_revision: Union[str, Sequence[str], None] = '93890040ddd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('marital_status', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('father_name', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('mother_name', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('blood_type', sa.String(length=10), nullable=True))
    op.add_column('members', sa.Column('mother_lodge', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('collecting_lodge', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('initiation_certificate', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('initiation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('members', sa.Column('elevation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('members', sa.Column('exaltation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('members', sa.Column('installation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('members', sa.Column('affiliation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('members', sa.Column('regularization_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('members', sa.Column('dismissal_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # --- Data Migration Start ---
    op.execute("""
        UPDATE members SET initiation_data = jsonb_build_object('data_sessao', TO_CHAR(initiation_date, 'YYYY-MM-DD')) WHERE initiation_date IS NOT NULL;
        UPDATE members SET elevation_data = jsonb_build_object('data_sessao', TO_CHAR(elevation_date, 'YYYY-MM-DD')) WHERE elevation_date IS NOT NULL;
        UPDATE members SET exaltation_data = jsonb_build_object('data_sessao', TO_CHAR(exaltation_date, 'YYYY-MM-DD')) WHERE exaltation_date IS NOT NULL;
        UPDATE members SET installation_data = jsonb_build_object('data_sessao', TO_CHAR(installation_date, 'YYYY-MM-DD')) WHERE installation_date IS NOT NULL;
        UPDATE members SET affiliation_data = jsonb_build_object('data_sessao', TO_CHAR(affiliation_date, 'YYYY-MM-DD')) WHERE affiliation_date IS NOT NULL;
        UPDATE members SET regularization_data = jsonb_build_object('data_sessao', TO_CHAR(regularization_date, 'YYYY-MM-DD')) WHERE regularization_date IS NOT NULL;
    """)
    # --- Data Migration End ---

    op.drop_column('members', 'regularization_date')
    op.drop_column('members', 'installation_date')
    op.drop_column('members', 'initiation_date')
    op.drop_column('members', 'elevation_date')
    op.drop_column('members', 'exaltation_date')
    op.drop_column('members', 'affiliation_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('affiliation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('exaltation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('elevation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('initiation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('installation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('regularization_date', sa.DATE(), autoincrement=False, nullable=True))

    # --- Data Downgrade Start ---
    op.execute("""
        UPDATE members SET initiation_date = (initiation_data->>'data_sessao')::DATE WHERE initiation_data->>'data_sessao' IS NOT NULL;
        UPDATE members SET elevation_date = (elevation_data->>'data_sessao')::DATE WHERE elevation_data->>'data_sessao' IS NOT NULL;
        UPDATE members SET exaltation_date = (exaltation_data->>'data_sessao')::DATE WHERE exaltation_data->>'data_sessao' IS NOT NULL;
        UPDATE members SET installation_date = (installation_data->>'data_sessao')::DATE WHERE installation_data->>'data_sessao' IS NOT NULL;
        UPDATE members SET affiliation_date = (affiliation_data->>'data_sessao')::DATE WHERE affiliation_data->>'data_sessao' IS NOT NULL;
        UPDATE members SET regularization_date = (regularization_data->>'data_sessao')::DATE WHERE regularization_data->>'data_sessao' IS NOT NULL;
    """)
    # --- Data Downgrade End ---

    op.drop_column('members', 'dismissal_data')
    op.drop_column('members', 'regularization_data')
    op.drop_column('members', 'affiliation_data')
    op.drop_column('members', 'installation_data')
    op.drop_column('members', 'exaltation_data')
    op.drop_column('members', 'elevation_data')
    op.drop_column('members', 'initiation_data')
    op.drop_column('members', 'initiation_certificate')
    op.drop_column('members', 'collecting_lodge')
    op.drop_column('members', 'mother_lodge')
    op.drop_column('members', 'blood_type')
    op.drop_column('members', 'mother_name')
    op.drop_column('members', 'father_name')
    op.drop_column('members', 'marital_status')
    # ### end Alembic commands ###
