"""add balaustre_file_path to masonic_sessions

Revision ID: 151e48635b63
Revises: cc3288d96128
Create Date: 2026-06-17 09:13:19.397087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151e48635b63'
down_revision: Union[str, Sequence[str], None] = 'cc3288d96128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masonic_sessions', sa.Column('balaustre_file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masonic_sessions', 'balaustre_file_path')
    # ### end Alembic commands ###
