"""Add previous_settings to Lodge and Obedience

Revision ID: 16938d1da1f6
Revises: 49fd7332097b
Create Date: 2026-06-13 11:06:52.650483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16938d1da1f6'
down_revision: Union[str, Sequence[str], None] = '49fd7332097b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('previous_settings', sa.JSON(), nullable=True, comment='Backup de configurações de fábrica'))
    op.add_column('obediences', sa.Column('previous_settings', sa.JSON(), nullable=True, comment='Backup de configurações de fábrica'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obediences', 'previous_settings')
    op.drop_column('lodges', 'previous_settings')
    # ### end Alembic commands ###
