"""add_logo_path_and_numeric_degree

Revision ID: 19fa7d91b5f2
Revises: 4fee604536b4
Create Date: 2026-07-07 13:28:00.149121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fa7d91b5f2'
down_revision: Union[str, Sequence[str], None] = '4fee604536b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('logo_path', sa.String(length=255), nullable=True, comment='Caminho relativo para a imagem do logo da loja no storage'))
    op.add_column('members', sa.Column('numeric_degree', sa.Integer(), nullable=True, comment='Grau numérico de 1 a 33'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'numeric_degree')
    op.drop_column('lodges', 'logo_path')
    # ### end Alembic commands ###
