'''update_visitor_model

Revision ID: 1bfe2df6f103
Revises: cce49183e52c
Create Date: 2025-12-03 07:39:23.939845

'''
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bfe2df6f103'
down_revision = 'cce49183e52c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('cim', sa.String(length=50), nullable=False))
    op.add_column('visitors', sa.Column('degree', sa.Enum('APPRENTICE', 'FELLOW', 'MASTER', 'INSTALLED_MASTER', name='visitor_degree_enum'), nullable=False))
    op.add_column('visitors', sa.Column('origin_lodge_id', sa.Integer(), nullable=True))
    op.add_column('visitors', sa.Column('manual_lodge_name', sa.String(length=255), nullable=True))
    op.add_column('visitors', sa.Column('manual_lodge_number', sa.String(length=50), nullable=True))
    op.add_column('visitors', sa.Column('manual_lodge_obedience', sa.String(length=100), nullable=True))
    op.add_column('visitors', sa.Column('global_visitor_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_visitors_cim'), 'visitors', ['cim'], unique=True)
    op.create_index(op.f('ix_visitors_global_visitor_id'), 'visitors', ['global_visitor_id'], unique=False)
    op.drop_column('visitors', 'origin_lodge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('origin_lodge', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_index(op.f('ix_visitors_global_visitor_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_cim'), table_name='visitors')
    op.drop_column('visitors', 'global_visitor_id')
    op.drop_column('visitors', 'manual_lodge_obedience')
    op.drop_column('visitors', 'manual_lodge_number')
    op.drop_column('visitors', 'manual_lodge_name')
    op.drop_column('visitors', 'origin_lodge_id')
    op.drop_column('visitors', 'degree')
    op.drop_column('visitors', 'cim')
    # ### end Alembic commands ###
