'''Add administration_id to RoleHistory

Revision ID: 1f4ea8e6f22f
Revises: 26b16ab47ebf
Create Date: 2025-12-12 09:22:43.807204

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4ea8e6f22f'
down_revision = '26b16ab47ebf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
