"""Add Cashless module models

Revision ID: 250665656a1f
Revises: caf1d9580abd
Create Date: 2026-06-27 11:14:44.865648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250665656a1f'
down_revision: Union[str, Sequence[str], None] = 'caf1d9580abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashless_mercadopago_webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False, comment='ID único do evento na API do MP'),
    sa.Column('type', sa.String(length=100), nullable=False, comment='Tipo do evento (ex: payment.created)'),
    sa.Column('status', sa.Enum('Pendente', 'Processado', 'Falhou', 'Ignorado', name='webhookstatusenum'), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True, comment='JSON completo recebido'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashless_mercadopago_webhooks_event_id'), 'cashless_mercadopago_webhooks', ['event_id'], unique=True)
    op.create_index(op.f('ix_cashless_mercadopago_webhooks_id'), 'cashless_mercadopago_webhooks', ['id'], unique=False)
    op.create_table('cashless_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('stock >= 0', name='chk_product_stock_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashless_products_id'), 'cashless_products', ['id'], unique=False)
    op.create_table('cashless_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identification_key', sa.String(length=50), nullable=False, comment='CIM para Membros, CPF para Externos'),
    sa.Column('type', sa.Enum('Membro', 'Externo', name='cashlessusertypeenum'), nullable=False),
    sa.Column('profile_type', sa.Enum('Cliente', 'Caixa', 'Gerente', name='cashlessprofiletypeenum'), nullable=False),
    sa.Column('pin', sa.String(length=255), nullable=True, comment='Senha numérica para Caixas/Gerentes'),
    sa.Column('responsible_member_id', sa.Integer(), nullable=True, comment='Maçom responsável (Anfitrião) pelo consumo deste usuário'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['responsible_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashless_users_id'), 'cashless_users', ['id'], unique=False)
    op.create_index(op.f('ix_cashless_users_identification_key'), 'cashless_users', ['identification_key'], unique=True)
    op.create_table('cashless_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cashless_user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('App Autoatendimento', 'PDV Balcão', name='orderchannelenum'), nullable=False),
    sa.Column('status', sa.Enum('Criado', 'Aguardando Retirada', 'Entregue', 'Cancelado', name='orderstatusenum'), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cashless_user_id'], ['cashless_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashless_orders_cashless_user_id'), 'cashless_orders', ['cashless_user_id'], unique=False)
    op.create_index(op.f('ix_cashless_orders_id'), 'cashless_orders', ['id'], unique=False)
    op.create_table('cashless_wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cashless_user_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False, comment='Saldo atual. Atualizado via trigger ou sum dinâmico'),
    sa.Column('allow_negative_balance', sa.Boolean(), nullable=False, comment='Permite Pós-Pago (Fatura) se True'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cashless_user_id'], ['cashless_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cashless_user_id')
    )
    op.create_index(op.f('ix_cashless_wallets_id'), 'cashless_wallets', ['id'], unique=False)
    op.create_table('cashless_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['cashless_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['cashless_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashless_order_items_id'), 'cashless_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_cashless_order_items_order_id'), 'cashless_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_cashless_order_items_product_id'), 'cashless_order_items', ['product_id'], unique=False)
    op.create_table('cashless_stock_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('Entrada Compra', 'Entrada Ajuste', 'Saída Venda', 'Quebra', 'Perda', 'Cortesia', name='stockmovementtypeenum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=True, comment='Quem registrou a movimentação'),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['cashless_users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['cashless_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['cashless_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashless_stock_movements_id'), 'cashless_stock_movements', ['id'], unique=False)
    op.create_index(op.f('ix_cashless_stock_movements_product_id'), 'cashless_stock_movements', ['product_id'], unique=False)
    op.create_table('cashless_wallet_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('Crédito PIX', 'Crédito Maquininha', 'Crédito Dinheiro', 'Débito Consumo', 'Débito Cashout', 'Ajuste Crédito', 'Ajuste Débito', name='wallettransactiontypeenum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gateway_id', sa.String(length=255), nullable=True, comment='ID da transação no Mercado Pago, se aplicável'),
    sa.Column('order_id', sa.String(length=36), nullable=True, comment='Pedido associado ao consumo'),
    sa.Column('operator_id', sa.String(length=36), nullable=True, comment='Quem operou a transação (Caixa)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['cashless_users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['cashless_orders.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['cashless_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashless_wallet_transactions_id'), 'cashless_wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_cashless_wallet_transactions_wallet_id'), 'cashless_wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cashless_wallet_transactions_wallet_id'), table_name='cashless_wallet_transactions')
    op.drop_index(op.f('ix_cashless_wallet_transactions_id'), table_name='cashless_wallet_transactions')
    op.drop_table('cashless_wallet_transactions')
    op.drop_index(op.f('ix_cashless_stock_movements_product_id'), table_name='cashless_stock_movements')
    op.drop_index(op.f('ix_cashless_stock_movements_id'), table_name='cashless_stock_movements')
    op.drop_table('cashless_stock_movements')
    op.drop_index(op.f('ix_cashless_order_items_product_id'), table_name='cashless_order_items')
    op.drop_index(op.f('ix_cashless_order_items_order_id'), table_name='cashless_order_items')
    op.drop_index(op.f('ix_cashless_order_items_id'), table_name='cashless_order_items')
    op.drop_table('cashless_order_items')
    op.drop_index(op.f('ix_cashless_wallets_id'), table_name='cashless_wallets')
    op.drop_table('cashless_wallets')
    op.drop_index(op.f('ix_cashless_orders_id'), table_name='cashless_orders')
    op.drop_index(op.f('ix_cashless_orders_cashless_user_id'), table_name='cashless_orders')
    op.drop_table('cashless_orders')
    op.drop_index(op.f('ix_cashless_users_identification_key'), table_name='cashless_users')
    op.drop_index(op.f('ix_cashless_users_id'), table_name='cashless_users')
    op.drop_table('cashless_users')
    op.drop_index(op.f('ix_cashless_products_id'), table_name='cashless_products')
    op.drop_table('cashless_products')
    op.drop_index(op.f('ix_cashless_mercadopago_webhooks_id'), table_name='cashless_mercadopago_webhooks')
    op.drop_index(op.f('ix_cashless_mercadopago_webhooks_event_id'), table_name='cashless_mercadopago_webhooks')
    op.drop_table('cashless_mercadopago_webhooks')
    # ### end Alembic commands ###
