'''Add document_settings to Lodge

Revision ID: 26b16ab47ebf
Revises: 6a274ff20605
Create Date: 2025-12-11 10:02:29.348756

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b16ab47ebf'
down_revision = '6a274ff20605'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('document_settings', sa.JSON(), nullable=True))
    op.add_column('notices', sa.Column('type', sa.Enum('Aviso', 'Notícia', name='notice_type_enum'), nullable=False))
    op.add_column('notices', sa.Column('publication_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notices', 'publications', ['publication_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notices', type_='foreignkey')
    op.drop_column('notices', 'publication_id')
    op.drop_column('notices', 'type')
    op.drop_column('lodges', 'document_settings')
    # ### end Alembic commands ###
