'''Update default logo_size to 12pt

Revision ID: 32c483878082
Revises: 6d6ddcf5e533
Create Date: 2025-12-14 11:41:57.814281

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c483878082'
down_revision = '6d6ddcf5e533'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
