'''feat: Adicionar tabela Visit para registro de visitação

Revision ID: 3472cd8ec2b7
Revises: ff32fa4e7a71
Create Date: 2025-11-21 11:33:42.804826

'''
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3472cd8ec2b7'
down_revision = 'ff32fa4e7a71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('home_lodge_id', sa.Integer(), nullable=False),
    sa.Column('visited_lodge_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['home_lodge_id'], ['lodges.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['masonic_sessions.id'], ),
    sa.ForeignKeyConstraint(['visited_lodge_id'], ['lodges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'session_id', name='_member_session_visit_uc')
    )
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_visit_date'), 'visits', ['visit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visit_date'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
