"""Create initial database schema and apply naming directives

Revision ID: 45d98617120e
Revises:
Create Date: 2025-11-07 11:03:34.758382

"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "45d98617120e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lodges", sa.Column("cnpj", sa.String(length=18), nullable=True))
    op.drop_index(op.f("tax_id"), table_name="lodges")
    op.create_unique_constraint(None, "lodges", ["cnpj"])
    op.drop_column("lodges", "tax_id")
    op.add_column("obediences", sa.Column("cnpj", sa.String(length=18), nullable=True))
    op.alter_column(
        "obediences",
        "technical_contact_name",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        nullable=False,
    )
    op.alter_column(
        "obediences",
        "technical_contact_email",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        nullable=False,
    )
    op.drop_index(op.f("tax_id"), table_name="obediences")
    op.create_unique_constraint(None, "obediences", ["cnpj"])
    op.drop_column("obediences", "tax_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "obediences", sa.Column("tax_id", mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=18), nullable=True)
    )
    op.drop_constraint(None, "obediences", type_="unique")
    op.create_index(op.f("tax_id"), "obediences", ["tax_id"], unique=True)
    op.alter_column(
        "obediences",
        "technical_contact_email",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        nullable=True,
    )
    op.alter_column(
        "obediences",
        "technical_contact_name",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        nullable=True,
    )
    op.drop_column("obediences", "cnpj")
    op.add_column(
        "lodges", sa.Column("tax_id", mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=18), nullable=True)
    )
    op.drop_constraint(None, "lodges", type_="unique")
    op.create_index(op.f("tax_id"), "lodges", ["tax_id"], unique=True)
    op.drop_column("lodges", "cnpj")
    # ### end Alembic commands ###
