'''add_level_and_credential_to_roles

Revision ID: 4743c601d933
Revises: 5b2307ea2f85
Create Date: 2025-11-27 09:53:02.372905

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4743c601d933'
down_revision = '5b2307ea2f85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
