# -*- coding: utf-8 -*-
"""Add MasonicEvent and Diploma

Revision ID: 4782bb063bdc
Revises: 1269c4b09e73
Create Date: 2026-07-23 11:44:19.739526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4782bb063bdc'
down_revision: Union[str, Sequence[str], None] = '1269c4b09e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masonic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('INITIATION', 'ELEVATION', 'EXALTATION', 'INSTALLATION', 'AFFILIATION', 'REGULARIZATION', 'DISMISSAL', name='event_type_enum'), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('process_number', sa.String(length=100), nullable=True),
    sa.Column('registry_number', sa.String(length=100), nullable=True),
    sa.Column('placet_number', sa.String(length=50), nullable=True),
    sa.Column('quit_placet_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masonic_events_id'), 'masonic_events', ['id'], unique=False)
    op.create_table('diplomas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masonic_event_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('diploma_type', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('registry_number', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['masonic_event_id'], ['masonic_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diplomas_id'), 'diplomas', ['id'], unique=False)
    op.add_column('members', sa.Column('collecting_lodge_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'members', 'lodges', ['collecting_lodge_id'], ['id'], ondelete='SET NULL')

    # --- CUSTOM DATA MIGRATION START ---
    connection = op.get_bind()
    
    # 1. Fetch all existing lodges to map by name or number
    lodges_result = connection.execute(sa.text("SELECT id, lodge_name, lodge_number FROM lodges"))
    lodges = []
    for row in lodges_result:
        lodges.append({"id": row[0], "name": row[1], "number": row[2]})
        
    def find_lodge_id(lodge_string: str) -> int:
        if not lodge_string:
            return None
        # Try to match by number first if it's like "Loja ... nº 1234"
        import re
        num_match = re.search(r'n[ºo°]\s*(\d+)', lodge_string, re.IGNORECASE)
        if num_match:
            num = num_match.group(1)
            for l in lodges:
                if str(l["number"]) == num:
                    return l["id"]
        # Otherwise match by substring
        for l in lodges:
            if l["name"].lower() in lodge_string.lower():
                return l["id"]
        return None

    # 2. Fetch all members
    members_result = connection.execute(sa.text(
        "SELECT id, mother_lodge, collecting_lodge, initiation_certificate, "
        "initiation_data, elevation_data, exaltation_data, installation_data, "
        "affiliation_data, regularization_data, dismissal_data FROM members"
    ))
    
    events_to_insert = []
    members_to_update = []
    
    for row in members_result:
        m_id = row[0]
        mother_lodge = row[1]
        collecting_lodge = row[2]
        init_cert = row[3]
        
        mother_lodge_id = find_lodge_id(mother_lodge)
        collecting_lodge_id = find_lodge_id(collecting_lodge)
        
        if collecting_lodge_id:
            members_to_update.append({"id": m_id, "col_id": collecting_lodge_id})
            
        def process_event(event_type: str, json_data: dict, default_lodge_id: int = None):
            if not json_data:
                return
            # Se tiver 'loja' no json, tentar mapear
            lodge_str = json_data.get('loja', '')
            l_id = find_lodge_id(lodge_str) if lodge_str else default_lodge_id
            
            # extract dates
            def parse_date(d):
                if not d: return None
                # Basic iso format fallback
                try:
                    from datetime import datetime
                    if 'T' in d: return d.split('T')[0]
                    return datetime.strptime(d, '%Y-%m-%d').date()
                except:
                    return None
                    
            events_to_insert.append({
                "member_id": m_id,
                "lodge_id": l_id,
                "event_type": event_type,
                "session_date": parse_date(json_data.get('data_sessao')),
                "entry_date": parse_date(json_data.get('data_entrada')),
                "process_number": json_data.get('processo'),
                "registry_number": json_data.get('registro'),
                "placet_number": json_data.get('placet'),
                "quit_placet_number": json_data.get('quite_placet')
            })

        # Process each block
        process_event("INITIATION", row[4], mother_lodge_id)
        process_event("ELEVATION", row[5], mother_lodge_id)
        process_event("EXALTATION", row[6], mother_lodge_id)
        process_event("INSTALLATION", row[7], mother_lodge_id)
        process_event("AFFILIATION", row[8], None)
        process_event("REGULARIZATION", row[9], None)
        process_event("DISMISSAL", row[10], mother_lodge_id)
        
        # se init_cert não estava no JSON, e existe iniciação, injetar
        if init_cert and row[4] and not row[4].get('placet'):
            for ev in events_to_insert:
                if ev['member_id'] == m_id and ev['event_type'] == "INITIATION":
                    ev['placet_number'] = init_cert
                    break

    # 3. Insert Events
    if events_to_insert:
        from sqlalchemy.sql import table, column
        masonic_events_table = table(
            'masonic_events',
            column('member_id', sa.Integer),
            column('lodge_id', sa.Integer),
            column('event_type', sa.String),
            column('session_date', sa.Date),
            column('entry_date', sa.Date),
            column('process_number', sa.String),
            column('registry_number', sa.String),
            column('placet_number', sa.String),
            column('quit_placet_number', sa.String)
        )
        op.bulk_insert(masonic_events_table, events_to_insert)

    # 4. Update Members Collecting Lodge
    for m_upd in members_to_update:
        connection.execute(sa.text(f"UPDATE members SET collecting_lodge_id = {m_upd['col_id']} WHERE id = {m_upd['id']}"))
        
    # --- CUSTOM DATA MIGRATION END ---
    op.drop_column('members', 'collecting_lodge')
    op.drop_column('members', 'exaltation_data')
    op.drop_column('members', 'dismissal_data')
    op.drop_column('members', 'mother_lodge')
    op.drop_column('members', 'initiation_certificate')
    op.drop_column('members', 'installation_data')
    op.drop_column('members', 'initiation_data')
    op.drop_column('members', 'elevation_data')
    op.drop_column('members', 'regularization_data')
    op.drop_column('members', 'affiliation_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('affiliation_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('regularization_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('elevation_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('initiation_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('installation_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('initiation_certificate', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('mother_lodge', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('dismissal_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('exaltation_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('collecting_lodge', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'collecting_lodge_id')
    op.drop_index(op.f('ix_diplomas_id'), table_name='diplomas')
    op.drop_table('diplomas')
    op.drop_index(op.f('ix_masonic_events_id'), table_name='masonic_events')
    op.drop_table('masonic_events')

    # We cannot easily reverse the masonic_events back into json blobs precisely.
    # Data loss might occur on downgrade for Masonic events.
    # ### end Alembic commands ###
