"""add whatsapp_settings to lodge

Revision ID: 4fee604536b4
Revises: 6b881796dc47
Create Date: 2026-07-01 08:37:58.141124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fee604536b4'
down_revision: Union[str, Sequence[str], None] = '6b881796dc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('whatsapp_settings', sa.JSON(), nullable=True, comment='Configurações granulares (JSON) do Módulo de WhatsApp para a Loja'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodges', 'whatsapp_settings')
    # ### end Alembic commands ###
