'''fix_administration_table_defaults

Revision ID: 5833d58774f5
Revises: d41be11138e3
Create Date: 2025-12-08 08:51:48.939769

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5833d58774f5'
down_revision = 'd41be11138e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_administrations_id'), 'administrations', ['id'], unique=False)
    op.create_index(op.f('ix_administrations_lodge_id'), 'administrations', ['lodge_id'], unique=False)
    op.create_foreign_key(None, 'masonic_sessions', 'administrations', ['administration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'masonic_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_administrations_lodge_id'), table_name='administrations')
    op.drop_index(op.f('ix_administrations_id'), table_name='administrations')
    # ### end Alembic commands ###
