"""add custom_holidays to lodge

Revision ID: 58b1ecdda6fc
Revises: 5243265ee466
Create Date: 2026-06-17 10:03:36.167976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b1ecdda6fc'
down_revision: Union[str, Sequence[str], None] = '5243265ee466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('custom_holidays', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodges', 'custom_holidays')
    # ### end Alembic commands ###
