"""rbac_schema_update

Revision ID: 5b2307ea2f85
Revises: e00264862a7b
Create Date: 2025-11-27 09:15:31.413922

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5b2307ea2f85"
down_revision = "e00264862a7b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_permission_exceptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=True),
        sa.Column("obedience_id", sa.Integer(), nullable=True),
        sa.Column("exception_type", sa.Enum("GRANT", "REVOKE", name="exceptiontypeenum"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(lodge_id IS NOT NULL AND obedience_id IS NULL) OR (lodge_id IS NULL AND obedience_id IS NOT NULL)",
            name="chk_exception_single_context",
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["obedience_id"],
            ["obediences.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "member_id", "permission_id", "lodge_id", "obedience_id", name="_member_permission_context_uc"
        ),
    )
    op.create_index(op.f("ix_member_permission_exceptions_id"), "member_permission_exceptions", ["id"], unique=False)
    op.add_column("member_lodge_associations", sa.Column("start_date", sa.Date(), nullable=True))
    op.add_column("member_lodge_associations", sa.Column("end_date", sa.Date(), nullable=True))
    op.add_column("member_obedience_associations", sa.Column("start_date", sa.Date(), nullable=True))
    op.add_column("member_obedience_associations", sa.Column("end_date", sa.Date(), nullable=True))
    op.add_column("permissions", sa.Column("min_credential", sa.Integer(), nullable=False))
    op.add_column("roles", sa.Column("level", sa.Integer(), nullable=False))
    op.add_column("roles", sa.Column("base_credential", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "base_credential")
    op.drop_column("roles", "level")
    op.drop_column("permissions", "min_credential")
    op.drop_column("member_obedience_associations", "end_date")
    op.drop_column("member_obedience_associations", "start_date")
    op.drop_column("member_lodge_associations", "end_date")
    op.drop_column("member_lodge_associations", "start_date")
    op.drop_index(op.f("ix_member_permission_exceptions_id"), table_name="member_permission_exceptions")
    op.drop_table("member_permission_exceptions")
    # ### end Alembic commands ###
