'''update_rite_names

Revision ID: 6709ef750279
Revises: 71e30601c7bc
Create Date: 2025-11-27 13:56:10.408161

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6709ef750279'
down_revision = '71e30601c7bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
