'''Update Publication model for PDF support

Revision ID: 6a274ff20605
Revises: 869e0ff797ee
Create Date: 2025-12-10 09:04:28.256709

'''
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a274ff20605'
down_revision = '869e0ff797ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('file_path', sa.String(length=512), nullable=False))
    op.add_column('publications', sa.Column('file_size', sa.Integer(), nullable=True))
    op.alter_column('publications', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_column('publications', 'excerpt')
    op.drop_column('publications', 'cover_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('cover_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=True))
    op.add_column('publications', sa.Column('excerpt', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.alter_column('publications', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_column('publications', 'file_size')
    op.drop_column('publications', 'file_path')
    # ### end Alembic commands ###
