"""verify_models

Revision ID: 6b4cedcc69e5
Revises: 8f562cbea76a
Create Date: 2026-06-05 10:58:01.578466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4cedcc69e5'
down_revision: Union[str, Sequence[str], None] = '8f562cbea76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('administrations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrations', 'updated_at')
    op.drop_column('administrations', 'created_at')
    # ### end Alembic commands ###
