'''add_temporary_role_assignments_to_session

Revision ID: 6d6ddcf5e533
Revises: fd6bd6dae1c8
Create Date: 2025-12-12 10:16:26.962397

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6ddcf5e533'
down_revision = 'fd6bd6dae1c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masonic_sessions', sa.Column('temporary_role_assignments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masonic_sessions', 'temporary_role_assignments')
    # ### end Alembic commands ###
