'''add_rer_rite

Revision ID: 71e30601c7bc
Revises: 768ad5da21df
Create Date: 2025-11-27 13:53:30.313863

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e30601c7bc'
down_revision = '768ad5da21df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
