'''update_enums_and_session_status

Revision ID: 768ad5da21df
Revises: 10fbdc48f3a2
Create Date: 2025-11-27 13:49:05.522003

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768ad5da21df'
down_revision = '10fbdc48f3a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
