"""Add 3-tier document engine models

Revision ID: 7a92977ec294
Revises: cde12949aa5c
Create Date: 2026-03-06 08:26:02.968288

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a92977ec294"
down_revision: str | Sequence[str] | None = "cde12949aa5c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_document_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("html_content", sa.Text(), nullable=False),
        sa.Column("header_html", sa.Text(), nullable=True),
        sa.Column("footer_html", sa.Text(), nullable=True),
        sa.Column("placeholders_schema", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_type"),
    )
    op.create_index(op.f("ix_global_document_templates_id"), "global_document_templates", ["id"], unique=False)
    op.create_table(
        "local_document_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("custom_html_content", sa.Text(), nullable=True),
        sa.Column("custom_header", sa.Text(), nullable=True),
        sa.Column("custom_footer", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lodge_id", "document_type", name="_lodge_document_type_uc"),
    )
    op.create_index(op.f("ix_local_document_templates_id"), "local_document_templates", ["id"], unique=False)
    op.create_index(
        op.f("ix_local_document_templates_lodge_id"), "local_document_templates", ["lodge_id"], unique=False
    )
    op.create_table(
        "document_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status", sa.Enum("DRAFT", "PENDING_SIGNATURES", "FINALIZED", name="document_status_enum"), nullable=False
        ),
        sa.Column("draft_html_content", sa.Text(), nullable=True),
        sa.Column("final_html_content", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["masonic_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_instances_id"), "document_instances", ["id"], unique=False)
    op.create_index(op.f("ix_document_instances_lodge_id"), "document_instances", ["lodge_id"], unique=False)
    op.create_index(op.f("ix_document_instances_session_id"), "document_instances", ["session_id"], unique=False)
    op.drop_index(op.f("ix_document_templates_id"), table_name="document_templates")
    op.drop_table("document_templates")
    op.add_column("document_signatures", sa.Column("document_instance_id", sa.Integer(), nullable=False))
    op.add_column("document_signatures", sa.Column("member_id", sa.Integer(), nullable=False))
    op.add_column("document_signatures", sa.Column("role", sa.String(length=100), nullable=False))
    op.add_column("document_signatures", sa.Column("digital_hash", sa.String(length=64), nullable=False))
    op.drop_constraint(op.f("document_signatures_document_id_key"), "document_signatures", type_="unique")
    op.drop_index(op.f("ix_document_signatures_signature_hash"), table_name="document_signatures")
    op.create_index(op.f("ix_document_signatures_digital_hash"), "document_signatures", ["digital_hash"], unique=True)
    op.create_index(
        op.f("ix_document_signatures_document_instance_id"),
        "document_signatures",
        ["document_instance_id"],
        unique=False,
    )
    op.drop_constraint(op.f("document_signatures_document_id_fkey"), "document_signatures", type_="foreignkey")
    op.drop_constraint(op.f("document_signatures_signed_by_id_fkey"), "document_signatures", type_="foreignkey")
    op.create_foreign_key(None, "document_signatures", "members", ["member_id"], ["id"])
    op.create_foreign_key(None, "document_signatures", "document_instances", ["document_instance_id"], ["id"])
    op.drop_column("document_signatures", "signature_hash")
    op.drop_column("document_signatures", "document_id")
    op.drop_column("document_signatures", "signed_by_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_signatures", sa.Column("signed_by_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("document_signatures", sa.Column("document_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(
        "document_signatures", sa.Column("signature_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "document_signatures", type_="foreignkey")
    op.drop_constraint(None, "document_signatures", type_="foreignkey")
    op.create_foreign_key(
        op.f("document_signatures_signed_by_id_fkey"), "document_signatures", "members", ["signed_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("document_signatures_document_id_fkey"), "document_signatures", "documents", ["document_id"], ["id"]
    )
    op.drop_index(op.f("ix_document_signatures_document_instance_id"), table_name="document_signatures")
    op.drop_index(op.f("ix_document_signatures_digital_hash"), table_name="document_signatures")
    op.create_index(
        op.f("ix_document_signatures_signature_hash"), "document_signatures", ["signature_hash"], unique=True
    )
    op.create_unique_constraint(
        op.f("document_signatures_document_id_key"),
        "document_signatures",
        ["document_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("document_signatures", "digital_hash")
    op.drop_column("document_signatures", "role")
    op.drop_column("document_signatures", "member_id")
    op.drop_column("document_signatures", "document_instance_id")
    op.create_table(
        "document_templates",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_templates_pkey")),
        sa.UniqueConstraint(
            "type", name=op.f("document_templates_type_key"), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    op.create_index(op.f("ix_document_templates_id"), "document_templates", ["id"], unique=False)
    op.drop_index(op.f("ix_document_instances_session_id"), table_name="document_instances")
    op.drop_index(op.f("ix_document_instances_lodge_id"), table_name="document_instances")
    op.drop_index(op.f("ix_document_instances_id"), table_name="document_instances")
    op.drop_table("document_instances")
    op.drop_index(op.f("ix_local_document_templates_lodge_id"), table_name="local_document_templates")
    op.drop_index(op.f("ix_local_document_templates_id"), table_name="local_document_templates")
    op.drop_table("local_document_templates")
    op.drop_index(op.f("ix_global_document_templates_id"), table_name="global_document_templates")
    op.drop_table("global_document_templates")
    # ### end Alembic commands ###
