"""Add raw_lodge_name to MasonicEvent

Revision ID: 7fc2c4e223fd
Revises: 4782bb063bdc
Create Date: 2026-07-24 17:18:35.521661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc2c4e223fd'
down_revision: Union[str, Sequence[str], None] = '4782bb063bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masonic_events', sa.Column('raw_lodge_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masonic_events', 'raw_lodge_name')
    # ### end Alembic commands ###
