"""Add session_weeks and is_manually_modified

Revision ID: 863fa342e9d5
Revises: 58b1ecdda6fc
Create Date: 2026-06-17 10:30:13.054069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863fa342e9d5'
down_revision: Union[str, Sequence[str], None] = '58b1ecdda6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('session_weeks', sa.JSON(), nullable=True, comment='Ex: [1, 3] para primeira e terceira semana'))
    op.add_column('masonic_sessions', sa.Column('is_manually_modified', sa.Boolean(), server_default='false', nullable=False, comment='Sessão teve a data alterada manualmente'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masonic_sessions', 'is_manually_modified')
    op.drop_column('lodges', 'session_weeks')
    # ### end Alembic commands ###
