'''add_session_type_and_subtype

Revision ID: 866540a09111
Revises: 10426a5c3186
Create Date: 2025-12-01 09:16:40.433633

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866540a09111'
down_revision = '10426a5c3186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masonic_sessions', sa.Column('type', sa.Enum('ORDINARY', 'MAGNA', 'EXTRAORDINARY', name='session_type_enum'), nullable=True))
    op.add_column('masonic_sessions', sa.Column('subtype', sa.Enum('REGULAR', 'ADMINISTRATIVE', 'FINANCE', 'AFFILIATION_REGULARIZATION', 'ELECTORAL', 'RITUALISTIC_BANQUET', 'INITIATION', 'ELEVATION', 'EXALTATION', 'INSTALLATION', 'INSTALLATION_WORSHIPFUL', 'STANDARD_CONSECRATION', 'LODGE_REGULARIZATION', 'TEMPLE_CONSECRATION', 'LOWTON_ADOPTION', 'MATRIMONIAL_CONSECRATION', 'FUNERAL_POMPS', 'CONFERENCE', 'LECTURE', 'FESTIVE', 'CIVIC_CULTURAL', 'GENERAL_GM_ELECTION', 'STATE_GM_ELECTION', 'DF_GM_ELECTION', 'FAMILY_COUNCIL', 'EX_OFFICIO_PLACET', 'STATUTE_CHANGE', 'RITE_CHANGE', 'ORIENT_CHANGE', 'DISTINCTIVE_TITLE_CHANGE', 'LODGE_MERGER', name='session_subtype_enum'), nullable=True))
    op.add_column('member_lodge_associations', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISABLED', name='memberstatusenum'), nullable=False))
    op.add_column('member_lodge_associations', sa.Column('member_class', sa.Enum('REGULAR', 'IRREGULAR', 'EMERITUS', 'REMITTED', 'HONORARY', name='memberclassenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_lodge_associations', 'member_class')
    op.drop_column('member_lodge_associations', 'status')
    op.drop_column('masonic_sessions', 'subtype')
    op.drop_column('masonic_sessions', 'type')
    # ### end Alembic commands ###
