"""Add ImportTemplate model

Revision ID: 868fdda27f99
Revises: fc753476b07d
Create Date: 2026-06-22 11:43:20.887587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868fdda27f99'
down_revision: Union[str, Sequence[str], None] = 'fc753476b07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do template (ex: Ficha GOB)'),
    sa.Column('potency', sa.String(length=100), nullable=True, comment='Potência associada'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='PDF, EXCEL, CSV'),
    sa.Column('cim_regex', sa.Text(), nullable=True, comment='RegEx para encontrar o CIM'),
    sa.Column('name_regex', sa.Text(), nullable=True, comment='RegEx para encontrar o Nome'),
    sa.Column('email_regex', sa.Text(), nullable=True, comment='RegEx para encontrar o E-mail'),
    sa.Column('degree_regex', sa.Text(), nullable=True, comment='RegEx para encontrar o Grau'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_import_templates_id'), 'import_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_templates_id'), table_name='import_templates')
    op.drop_table('import_templates')
    # ### end Alembic commands ###
