'''Add Publication model

Revision ID: 869e0ff797ee
Revises: b4340b073757
Create Date: 2025-12-10 09:01:30.153794

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869e0ff797ee'
down_revision = 'b4340b073757'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('Aviso', 'Notícia', 'Artigo', 'Boletim Oficial', name='publication_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('Rascunho', 'Pendente', 'Publicado', 'Rejeitado', 'Arquivado', name='publication_status_enum'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
