"""Add available_modules

Revision ID: 8f562cbea76a
Revises: 2f51e4dc4ad1
Create Date: 2026-04-29 07:56:50.225394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f562cbea76a'
down_revision: Union[str, Sequence[str], None] = '2f51e4dc4ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('available_modules', sa.JSON(), nullable=True))
    op.add_column('obediences', sa.Column('available_modules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obediences', 'available_modules')
    op.drop_column('lodges', 'available_modules')
    # ### end Alembic commands ###
