"""refactor_degrees

Revision ID: 93890040ddd7
Revises: 19fa7d91b5f2
Create Date: 2026-07-07 13:41:03.647804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""refactor_degrees

Revision ID: 93890040ddd7
Revises: 19fa7d91b5f2
Create Date: 2026-07-07 13:41:03.647804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93890040ddd7'
down_revision: Union[str, Sequence[str], None] = '19fa7d91b5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create new boolean columns first
    op.add_column('members', sa.Column('is_installed', sa.Boolean(), nullable=True, comment='Flag de Mestre Instalado'))
    op.add_column('visitors', sa.Column('is_installed', sa.Boolean(), nullable=True))
    
    # Migrate is_installed data (handling NULL degrees)
    op.execute("UPDATE members SET is_installed = COALESCE(degree = 'Mestre Instalado', FALSE)")
    op.execute("UPDATE visitors SET is_installed = COALESCE(degree = 'Mestre Instalado', FALSE)")
    
    # Set them to NOT NULL
    op.alter_column('members', 'is_installed', nullable=False)
    op.alter_column('visitors', 'is_installed', nullable=False)

    # Drop defaults before altering types to prevent DatatypeMismatch
    op.execute("ALTER TABLE entity_messages ALTER COLUMN minimum_degree DROP DEFAULT")
    op.execute("ALTER TABLE masonic_sessions ALTER COLUMN degree DROP DEFAULT")
    op.execute("ALTER TABLE members ALTER COLUMN degree DROP DEFAULT")
    op.execute("ALTER TABLE publications ALTER COLUMN minimum_degree DROP DEFAULT")
    op.execute("ALTER TABLE visitors ALTER COLUMN degree DROP DEFAULT")

    using_clause_degree = "CASE WHEN degree='Aprendiz' THEN 1 WHEN degree='Companheiro' THEN 2 WHEN degree='Mestre' THEN 3 WHEN degree='Mestre Instalado' THEN 3 ELSE 1 END"
    using_clause_min = "CASE WHEN minimum_degree='Aprendiz' THEN 1 WHEN minimum_degree='Companheiro' THEN 2 WHEN minimum_degree='Mestre' THEN 3 WHEN minimum_degree='Mestre Instalado' THEN 3 ELSE 1 END"

    op.alter_column('entity_messages', 'minimum_degree',
               type_=sa.Integer(),
               postgresql_using=using_clause_min,
               comment='Grau mínimo (1-33)',
               existing_nullable=False,
               server_default=sa.text('1'))
               
    op.alter_column('masonic_sessions', 'degree',
               type_=sa.Integer(),
               postgresql_using=using_clause_degree,
               comment='Grau da Sessão (1-33)',
               existing_nullable=False,
               server_default=sa.text('1'))
               
    op.alter_column('members', 'degree',
               type_=sa.Integer(),
               postgresql_using=using_clause_degree,
               nullable=False,
               comment='Grau Maçônico (1 a 33)',
               server_default=sa.text('1'))
               
    op.drop_column('members', 'numeric_degree')
    op.drop_column('members', 'philosophical_degree')
    
    op.alter_column('publications', 'minimum_degree',
               type_=sa.Integer(),
               postgresql_using=using_clause_min,
               comment='Grau mínimo para acesso (1-33)',
               existing_nullable=False,
               server_default=sa.text('1'))
               
    op.alter_column('visitors', 'degree',
               type_=sa.Integer(),
               postgresql_using=using_clause_degree,
               existing_nullable=False,
               server_default=sa.text('1'))
               
    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS degree_enum CASCADE;")
    op.execute("DROP TYPE IF EXISTS visitor_degree_enum CASCADE;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'degree',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='visitor_degree_enum'),
               existing_nullable=False)
    op.drop_column('visitors', 'is_installed')
    op.alter_column('publications', 'minimum_degree',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='degree_enum'),
               comment=None,
               existing_comment='Grau mínimo para acesso (1-33)',
               existing_nullable=False,
               existing_server_default=sa.text("'Aprendiz'::degree_enum"))
    op.add_column('members', sa.Column('philosophical_degree', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('numeric_degree', sa.INTEGER(), autoincrement=False, nullable=True, comment='Grau numérico de 1 a 33'))
    op.alter_column('members', 'degree',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='degree_enum'),
               nullable=True,
               comment=None,
               existing_comment='Grau Maçônico (1 a 33)')
    op.drop_column('members', 'is_installed')
    op.alter_column('masonic_sessions', 'degree',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='degree_enum'),
               comment=None,
               existing_comment='Grau da Sessão (1-33)',
               existing_nullable=False,
               existing_server_default=sa.text("'Aprendiz'::degree_enum"))
    op.alter_column('entity_messages', 'minimum_degree',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='degree_enum'),
               comment=None,
               existing_comment='Grau mínimo (1-33)',
               existing_nullable=False,
               existing_server_default=sa.text("'Aprendiz'::degree_enum"))
    # ### end Alembic commands ###
