"""add lodge recess and auto schedule

Revision ID: 9ff3f879203f
Revises: 151e48635b63
Create Date: 2026-06-17 09:51:21.753122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff3f879203f'
down_revision: Union[str, Sequence[str], None] = '151e48635b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lodge_recesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lodge_recesses_id'), 'lodge_recesses', ['id'], unique=False)
    op.add_column('lodges', sa.Column('auto_schedule_sessions', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodges', 'auto_schedule_sessions')
    op.drop_index(op.f('ix_lodge_recesses_id'), table_name='lodge_recesses')
    op.drop_table('lodge_recesses')
    # ### end Alembic commands ###
