"""add_degree_to_documents_and_sessions

Revision ID: a0dff2075963
Revises: 863fa342e9d5
Create Date: 2026-06-17 10:52:06.528680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0dff2075963'
down_revision: Union[str, Sequence[str], None] = '863fa342e9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_messages', sa.Column('minimum_degree', sa.Enum('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='degree_enum'), server_default='Aprendiz', nullable=False))
    op.add_column('masonic_sessions', sa.Column('degree', sa.Enum('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='degree_enum'), server_default='Aprendiz', nullable=False))
    op.add_column('publications', sa.Column('minimum_degree', sa.Enum('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='degree_enum'), server_default='Aprendiz', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'minimum_degree')
    op.drop_column('masonic_sessions', 'degree')
    op.drop_column('entity_messages', 'minimum_degree')
    # ### end Alembic commands ###
