"""add_whatsapp_group_id_to_lodge

Revision ID: c24f46e815ad
Revises: ec900aa6b3a6
Create Date: 2026-06-30 19:57:13.282077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24f46e815ad'
down_revision: Union[str, Sequence[str], None] = 'ec900aa6b3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('whatsapp_group_id', sa.String(length=255), nullable=True, comment='ID do grupo oficial do WhatsApp'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodges', 'whatsapp_group_id')
    # ### end Alembic commands ###
