"""Increase lodge_code size and make session fields nullable

Revision ID: c6b01ca9c3f4
Revises: f0c423b2f71e
Create Date: 2025-11-26 17:18:17.648068

"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "c6b01ca9c3f4"
down_revision = "f0c423b2f71e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lodges",
        "lodge_code",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lodges",
        "lodge_code",
        existing_type=sa.String(length=36),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
