"""remove_unique_cim

Revision ID: caf1d9580abd
Revises: 868fdda27f99
Create Date: 2026-06-26 10:12:30.166140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf1d9580abd'
down_revision: Union[str, Sequence[str], None] = '868fdda27f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_cim'), table_name='members')
    op.create_index(op.f('ix_members_cim'), 'members', ['cim'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_cim'), table_name='members')
    op.create_index(op.f('ix_members_cim'), 'members', ['cim'], unique=True)
    # ### end Alembic commands ###
