"""Drop documents module tables

Revision ID: cc3288d96128
Revises: dd92e1e4045b
Create Date: 2026-06-13 11:17:58.409627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc3288d96128'
down_revision: Union[str, Sequence[str], None] = 'dd92e1e4045b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_local_document_templates_id'), table_name='local_document_templates')
    op.drop_index(op.f('ix_local_document_templates_lodge_id'), table_name='local_document_templates')
    op.drop_table('local_document_templates')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_lodge_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_global_document_templates_id'), table_name='global_document_templates')
    op.drop_table('global_document_templates')
    op.drop_index(op.f('ix_document_signatures_digital_hash'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_document_instance_id'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_id'), table_name='document_signatures')
    op.drop_table('document_signatures')
    op.drop_index(op.f('ix_document_instances_id'), table_name='document_instances')
    op.drop_index(op.f('ix_document_instances_lodge_id'), table_name='document_instances')
    op.drop_index(op.f('ix_document_instances_session_id'), table_name='document_instances')
    op.drop_table('document_instances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lodge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING_SIGNATURES', 'FINALIZED', name='document_status_enum'), autoincrement=False, nullable=False),
    sa.Column('draft_html_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('final_html_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('element_text_overrides', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Adequações de texto por elemento: {"assunto": "Texto adequado...", "texto": "<p>..."}'),
    sa.ForeignKeyConstraint(['created_by_id'], ['members.id'], name=op.f('document_instances_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], name=op.f('document_instances_lodge_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['masonic_sessions.id'], name=op.f('document_instances_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_instances_pkey'))
    )
    op.create_index(op.f('ix_document_instances_session_id'), 'document_instances', ['session_id'], unique=False)
    op.create_index(op.f('ix_document_instances_lodge_id'), 'document_instances', ['lodge_id'], unique=False)
    op.create_index(op.f('ix_document_instances_id'), 'document_instances', ['id'], unique=False)
    op.create_table('document_signatures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('document_instance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('digital_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_instance_id'], ['document_instances.id'], name=op.f('document_signatures_document_instance_id_fkey')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('document_signatures_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_signatures_pkey'))
    )
    op.create_index(op.f('ix_document_signatures_id'), 'document_signatures', ['id'], unique=False)
    op.create_index(op.f('ix_document_signatures_document_instance_id'), 'document_signatures', ['document_instance_id'], unique=False)
    op.create_index(op.f('ix_document_signatures_digital_hash'), 'document_signatures', ['digital_hash'], unique=True)
    op.create_table('global_document_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('html_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('header_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('footer_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('placeholders_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('page_settings_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('structural_elements_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('element_configs_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('global_document_templates_pkey')),
    sa.UniqueConstraint('document_type', name=op.f('global_document_templates_document_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_global_document_templates_id'), 'global_document_templates', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('lodge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], name=op.f('documents_lodge_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['masonic_sessions.id'], name=op.f('documents_session_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by_member_id'], ['members.id'], name=op.f('documents_uploaded_by_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.create_index(op.f('ix_documents_lodge_id'), 'documents', ['lodge_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_table('local_document_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lodge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('custom_html_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_header', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_footer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('page_settings_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('structural_elements_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('element_configs_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], name=op.f('local_document_templates_lodge_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('local_document_templates_pkey')),
    sa.UniqueConstraint('lodge_id', 'document_type', name=op.f('_lodge_document_type_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_local_document_templates_lodge_id'), 'local_document_templates', ['lodge_id'], unique=False)
    op.create_index(op.f('ix_local_document_templates_id'), 'local_document_templates', ['id'], unique=False)
    # ### end Alembic commands ###
