'''add geofence_radius to lodge

Revision ID: cce49183e52c
Revises: e864dcae982d
Create Date: 2025-12-02 20:55:25.151814

'''
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cce49183e52c'
down_revision = 'e864dcae982d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classified_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classified_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classified_id'], ['classifieds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classified_photos_id'), 'classified_photos', ['id'], unique=False)
    op.add_column('classifieds', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('classifieds', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('classifieds', sa.Column('number', sa.String(length=50), nullable=True))
    op.add_column('classifieds', sa.Column('neighborhood', sa.String(length=100), nullable=True))
    op.add_column('classifieds', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('classifieds', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('classifieds', sa.Column('zip_code', sa.String(length=9), nullable=True))
    op.add_column('classifieds', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('classifieds', 'image_path')
    op.add_column('lodges', sa.Column('geofence_radius', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodges', 'geofence_radius')
    op.add_column('classifieds', sa.Column('image_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=True))
    op.drop_column('classifieds', 'expires_at')
    op.drop_column('classifieds', 'zip_code')
    op.drop_column('classifieds', 'state')
    op.drop_column('classifieds', 'city')
    op.drop_column('classifieds', 'neighborhood')
    op.drop_column('classifieds', 'number')
    op.drop_column('classifieds', 'street')
    op.drop_column('classifieds', 'contact_email')
    op.drop_index(op.f('ix_classified_photos_id'), table_name='classified_photos')
    op.drop_table('classified_photos')
    # ### end Alembic commands ###
