"""Initial schema

Revision ID: cde12949aa5c
Revises:
Create Date: 2026-03-04 11:37:33.057058

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cde12949aa5c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("isbn", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("publish_year", sa.Integer(), nullable=True),
        sa.Column("pages", sa.Integer(), nullable=True),
        sa.Column("cover_url", sa.String(length=512), nullable=True),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("required_degree", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("required_degree >= 1 AND required_degree <= 3", name="chk_book_required_degree"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=True)
    op.create_table(
        "document_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
    )
    op.create_index(op.f("ix_document_templates_id"), "document_templates", ["id"], unique=False)
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("cpf", sa.String(length=14), nullable=True),
        sa.Column("identity_document", sa.String(length=50), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("marriage_date", sa.Date(), nullable=True),
        sa.Column("street_address", sa.String(length=255), nullable=True),
        sa.Column("street_number", sa.String(length=50), nullable=True),
        sa.Column("neighborhood", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("zip_code", sa.String(length=9), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("place_of_birth", sa.String(length=100), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("religion", sa.String(length=100), nullable=True),
        sa.Column("education_level", sa.String(length=255), nullable=True),
        sa.Column("occupation", sa.String(length=255), nullable=True),
        sa.Column("workplace", sa.String(length=255), nullable=True),
        sa.Column("profile_picture_path", sa.String(length=255), nullable=True),
        sa.Column("cim", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "degree",
            sa.Enum("Aprendiz", "Companheiro", "Mestre", "Mestre Instalado", name="degree_enum"),
            nullable=True,
        ),
        sa.Column("initiation_date", sa.Date(), nullable=True),
        sa.Column("elevation_date", sa.Date(), nullable=True),
        sa.Column("exaltation_date", sa.Date(), nullable=True),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column("affiliation_date", sa.Date(), nullable=True),
        sa.Column("regularization_date", sa.Date(), nullable=True),
        sa.Column("philosophical_degree", sa.String(length=100), nullable=True),
        sa.Column(
            "registration_status",
            sa.Enum("Pendente", "Aprovado", "Rejeitado", name="registration_status_enum"),
            nullable=False,
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_members_cim"), "members", ["cim"], unique=True)
    op.create_index(op.f("ix_members_cpf"), "members", ["cpf"], unique=True)
    op.create_index(op.f("ix_members_email"), "members", ["email"], unique=True)
    op.create_index(op.f("ix_members_id"), "members", ["id"], unique=False)
    op.create_table(
        "obediences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("acronym", sa.String(length=50), nullable=True),
        sa.Column("type", sa.Enum("Federal", "Estadual", name="obediencetypeenum"), nullable=False),
        sa.Column("parent_obedience_id", sa.Integer(), nullable=True),
        sa.Column("cnpj", sa.String(length=18), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("street_address", sa.String(length=255), nullable=True),
        sa.Column("street_number", sa.String(length=20), nullable=True),
        sa.Column("address_complement", sa.String(length=100), nullable=True),
        sa.Column("neighborhood", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("zip_code", sa.String(length=9), nullable=True),
        sa.Column("technical_contact_name", sa.String(length=255), nullable=False),
        sa.Column("technical_contact_email", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_obedience_id"],
            ["obediences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("acronym"),
        sa.UniqueConstraint("cnpj"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_obediences_id"), "obediences", ["id"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("min_credential", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action"),
    )
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role_type", sa.Enum("Loja", "Obediência", "Subobediência", name="roletypeenum"), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("base_credential", sa.Integer(), nullable=False),
        sa.Column("applicable_rites", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("level >= 1 AND level <= 9", name="chk_role_level"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "super_admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_super_admins_email"), "super_admins", ["email"], unique=True)
    op.create_index(op.f("ix_super_admins_id"), "super_admins", ["id"], unique=False)
    op.create_index(op.f("ix_super_admins_username"), "super_admins", ["username"], unique=True)
    op.create_table(
        "visitors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("cim", sa.String(length=50), nullable=False),
        sa.Column(
            "degree",
            sa.Enum("Aprendiz", "Companheiro", "Mestre", "Mestre Instalado", name="visitor_degree_enum"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("cpf", sa.String(length=14), nullable=True),
        sa.Column("origin_lodge_id", sa.Integer(), nullable=True),
        sa.Column("manual_lodge_name", sa.String(length=255), nullable=True),
        sa.Column("manual_lodge_number", sa.String(length=50), nullable=True),
        sa.Column("manual_lodge_obedience", sa.String(length=100), nullable=True),
        sa.Column("global_visitor_id", sa.String(length=36), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
    )
    op.create_index(op.f("ix_visitors_cim"), "visitors", ["cim"], unique=True)
    op.create_index(op.f("ix_visitors_global_visitor_id"), "visitors", ["global_visitor_id"], unique=False)
    op.create_index(op.f("ix_visitors_id"), "visitors", ["id"], unique=False)
    op.create_table(
        "decorations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("award_date", sa.Date(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decorations_id"), "decorations", ["id"], unique=False)
    op.create_table(
        "family_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum("Esposa", "Filho", "Filha", "Pai", "Mãe", name="relationship_type_enum"),
            nullable=False,
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("is_deceased", sa.Boolean(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_family_members_id"), "family_members", ["id"], unique=False)
    op.create_table(
        "lodges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lodge_name", sa.String(length=255), nullable=False),
        sa.Column("lodge_title", sa.String(length=50), nullable=True),
        sa.Column("lodge_code", sa.String(length=36), nullable=False),
        sa.Column("lodge_number", sa.String(length=255), nullable=True),
        sa.Column("foundation_date", sa.Date(), nullable=True),
        sa.Column(
            "rite",
            sa.Enum(
                "Rito Escocês Antigo e Aceito",
                "Rito York",
                "Rito Schroder",
                "Rito Brasileiro",
                "Rito Moderno",
                "Rito Adonhiramita",
                "Rito Escocês Retificado",
                name="riteenum",
            ),
            nullable=True,
        ),
        sa.Column("obedience_id", sa.Integer(), nullable=False),
        sa.Column("subobedience_id", sa.Integer(), nullable=True),
        sa.Column("cnpj", sa.String(length=18), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("street_address", sa.String(length=255), nullable=True),
        sa.Column("street_number", sa.String(length=20), nullable=True),
        sa.Column("address_complement", sa.String(length=100), nullable=True),
        sa.Column("neighborhood", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("zip_code", sa.String(length=9), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("qr_code_id", sa.String(length=36), nullable=True),
        sa.Column("geofence_radius", sa.Integer(), nullable=True),
        sa.Column("custom_domain", sa.String(length=255), nullable=True),
        sa.Column("plan", sa.String(length=255), nullable=True),
        sa.Column("user_limit", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.Column(
            "session_day",
            sa.Enum(
                "Domingos",
                "Segundas-feiras",
                "Terças-feiras",
                "Quartas-feiras",
                "Quintas-feiras",
                "Sextas-feiras",
                "Sábados",
                name="session_day_enum",
            ),
            nullable=True,
        ),
        sa.Column("periodicity", sa.Enum("Semanal", "Quinzenal", "Mensal", name="periodicity_enum"), nullable=True),
        sa.Column("session_time", sa.Time(), nullable=True),
        sa.Column("technical_contact_name", sa.String(length=255), nullable=False),
        sa.Column("technical_contact_email", sa.String(length=255), nullable=False),
        sa.Column("document_settings", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("latitude >= -90 AND latitude <= 90", name="chk_lodge_latitude"),
        sa.CheckConstraint("longitude >= -180 AND longitude <= 180", name="chk_lodge_longitude"),
        sa.CheckConstraint("user_limit > 0", name="chk_lodge_user_limit"),
        sa.ForeignKeyConstraint(
            ["obedience_id"],
            ["obediences.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subobedience_id"],
            ["obediences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cnpj"),
        sa.UniqueConstraint("custom_domain"),
        sa.UniqueConstraint("qr_code_id"),
    )
    op.create_index(op.f("ix_lodges_id"), "lodges", ["id"], unique=False)
    op.create_index(op.f("ix_lodges_lodge_code"), "lodges", ["lodge_code"], unique=True)
    op.create_table(
        "member_obedience_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("obedience_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("end_date IS NULL OR end_date >= start_date", name="chk_obedience_assoc_dates"),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["obedience_id"],
            ["obediences.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "obedience_id", name="_member_obedience_uc"),
    )
    op.create_index(op.f("ix_member_obedience_associations_id"), "member_obedience_associations", ["id"], unique=False)
    op.create_table(
        "obediences_roles_association",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("obedience_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["obedience_id"],
            ["obediences.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "obedience_id"),
    )
    op.create_table(
        "roles_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "administrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_administrations_id"), "administrations", ["id"], unique=False)
    op.create_index(op.f("ix_administrations_lodge_id"), "administrations", ["lodge_id"], unique=False)
    op.create_table(
        "administrative_processes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_administrative_processes_id"), "administrative_processes", ["id"], unique=False)
    op.create_table(
        "calendars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calendars_id"), "calendars", ["id"], unique=False)
    op.create_index(op.f("ix_calendars_lodge_id"), "calendars", ["lodge_id"], unique=False)
    op.create_table(
        "classifieds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("contact_info", sa.String(length=255), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("street", sa.String(length=255), nullable=True),
        sa.Column("number", sa.String(length=50), nullable=True),
        sa.Column("neighborhood", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("zip_code", sa.String(length=9), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_classifieds_id"), "classifieds", ["id"], unique=False)
    op.create_index(op.f("ix_classifieds_lodge_id"), "classifieds", ["lodge_id"], unique=False)
    op.create_table(
        "committees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("committee_type", sa.Enum("PERMANENT", "TEMPORARY", name="committee_type_enum"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("president_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["president_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_committees_id"), "committees", ["id"], unique=False)
    op.create_table(
        "dining_scales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("position", sa.String(length=50), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dining_scales_id"), "dining_scales", ["id"], unique=False)
    op.create_index(op.f("ix_dining_scales_lodge_id"), "dining_scales", ["lodge_id"], unique=False)
    op.create_table(
        "financial_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_financial_categories_id"), "financial_categories", ["id"], unique=False)
    op.create_index(op.f("ix_financial_categories_lodge_id"), "financial_categories", ["lodge_id"], unique=False)
    op.create_table(
        "library_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("inventory_code", sa.String(length=100), nullable=True),
        sa.Column("condition", sa.Enum("Novo", "Bom", "Regular", "Ruim", name="book_condition_enum"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Disponível", "Emprestado", "Reservado", "Extraviado", name="item_status_enum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_library_items_id"), "library_items", ["id"], unique=False)
    op.create_index(op.f("ix_library_items_lodge_id"), "library_items", ["lodge_id"], unique=False)
    op.create_table(
        "lodge_financial_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("active_gateway", sa.String(length=50), nullable=False),
        sa.Column("gateway_api_key", sa.String(length=255), nullable=True),
        sa.Column("gateway_webhook_secret", sa.String(length=255), nullable=True),
        sa.Column("strict_budget_control", sa.Boolean(), nullable=True),
        sa.Column("recalculate_late_fees", sa.Boolean(), nullable=True),
        sa.Column("default_penalty_percent", sa.Float(), nullable=True),
        sa.Column("default_interest_percent", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lodge_financial_configs_id"), "lodge_financial_configs", ["id"], unique=False)
    op.create_index(op.f("ix_lodge_financial_configs_lodge_id"), "lodge_financial_configs", ["lodge_id"], unique=True)
    op.create_table(
        "member_lodge_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Enum("Ativo", "Inativo", "Desativado", name="memberstatusenum"), nullable=False),
        sa.Column(
            "member_class",
            sa.Enum("Regular", "Irregular", "Emérito", "Remido", "Honorário", name="memberclassenum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("end_date IS NULL OR end_date >= start_date", name="chk_lodge_assoc_dates"),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "lodge_id", name="_member_lodge_uc"),
    )
    op.create_index(op.f("ix_member_lodge_associations_id"), "member_lodge_associations", ["id"], unique=False)
    op.create_table(
        "member_permission_exceptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=True),
        sa.Column("obedience_id", sa.Integer(), nullable=True),
        sa.Column("exception_type", sa.Enum("Concedida", "Revogada", name="exceptiontypeenum"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(lodge_id IS NOT NULL AND obedience_id IS NULL) OR (lodge_id IS NULL AND obedience_id IS NOT NULL)",
            name="chk_exception_single_context",
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["obedience_id"],
            ["obediences.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "member_id", "permission_id", "lodge_id", "obedience_id", name="_member_permission_context_uc"
        ),
    )
    op.create_index(op.f("ix_member_permission_exceptions_id"), "member_permission_exceptions", ["id"], unique=False)
    op.create_table(
        "publications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("Regulamentos", "Atos", "Documentos", "Boletins", "Artigo", name="publication_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("Rascunho", "Pendente", "Publicado", "Rejeitado", "Arquivado", name="publication_status_enum"),
            nullable=False,
        ),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_publications_id"), "publications", ["id"], unique=False)
    op.create_table(
        "waitlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("request_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Aguardando", "Notificado", "Atendido", "Cancelado", "Expirado", name="waitlist_status_enum"),
            nullable=False,
        ),
        sa.Column("notification_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_waitlists_id"), "waitlists", ["id"], unique=False)
    op.create_table(
        "webmasters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("lodge_id", sa.Integer(), nullable=True),
        sa.Column("obedience_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(lodge_id IS NOT NULL AND obedience_id IS NULL) OR (lodge_id IS NULL AND obedience_id IS NOT NULL)",
            name="chk_webmaster_single_instance",
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["obedience_id"],
            ["obediences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_webmasters_id"), "webmasters", ["id"], unique=False)
    op.create_table(
        "annual_budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("budgeted_amount", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["financial_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_annual_budgets_category_id"), "annual_budgets", ["category_id"], unique=False)
    op.create_index(op.f("ix_annual_budgets_id"), "annual_budgets", ["id"], unique=False)
    op.create_index(op.f("ix_annual_budgets_lodge_id"), "annual_budgets", ["lodge_id"], unique=False)
    op.create_table(
        "classified_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("classified_id", sa.Integer(), nullable=False),
        sa.Column("image_path", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["classified_id"],
            ["classifieds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_classified_photos_id"), "classified_photos", ["id"], unique=False)
    op.create_table(
        "committee_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("committee_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_committee_members_id"), "committee_members", ["id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("calendar_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("end_time > start_time", name="chk_event_dates"),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["calendars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_index(op.f("ix_events_lodge_id"), "events", ["lodge_id"], unique=False)
    op.create_table(
        "financial_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("competency_date", sa.Date(), nullable=False),
        sa.Column("original_amount", sa.Float(), nullable=False),
        sa.Column("interest_amount", sa.Float(), nullable=True),
        sa.Column("penalty_amount", sa.Float(), nullable=True),
        sa.Column("discount_amount", sa.Float(), nullable=True),
        sa.Column("paid_amount", sa.Float(), nullable=True),
        sa.Column("gateway_id", sa.String(length=100), nullable=True),
        sa.Column("gateway_link", sa.String(length=255), nullable=True),
        sa.Column("gateway_barcode", sa.String(length=255), nullable=True),
        sa.Column("gateway_pix_qrcode", sa.Text(), nullable=True),
        sa.Column("gateway_status", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["financial_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_transactions_category_id"), "financial_transactions", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_financial_transactions_id"), "financial_transactions", ["id"], unique=False)
    op.create_index(op.f("ix_financial_transactions_lodge_id"), "financial_transactions", ["lodge_id"], unique=False)
    op.create_index(op.f("ix_financial_transactions_member_id"), "financial_transactions", ["member_id"], unique=False)
    op.create_table(
        "loans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("loan_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("return_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Enum("Ativo", "Devolvido", "Atrasado", name="loan_status_enum"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("due_date > loan_date", name="chk_loan_dates"),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["library_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loans_id"), "loans", ["id"], unique=False)
    op.create_table(
        "masonic_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("session_number", sa.Integer(), nullable=True),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("type", sa.Enum("ORDINARY", "MAGNA", "EXTRAORDINARY", name="session_type_enum"), nullable=True),
        sa.Column(
            "subtype",
            sa.Enum(
                "REGULAR",
                "ADMINISTRATIVE",
                "FINANCE",
                "AFFILIATION_REGULARIZATION",
                "ELECTORAL",
                "RITUALISTIC_BANQUET",
                "INITIATION",
                "ELEVATION",
                "EXALTATION",
                "INSTALLATION",
                "INSTALLATION_WORSHIPFUL",
                "STANDARD_CONSECRATION",
                "LODGE_REGULARIZATION",
                "TEMPLE_CONSECRATION",
                "LOWTON_ADOPTION",
                "MATRIMONIAL_CONSECRATION",
                "FUNERAL_POMPS",
                "CONFERENCE",
                "LECTURE",
                "FESTIVE",
                "CIVIC_CULTURAL",
                "GENERAL_GM_ELECTION",
                "STATE_GM_ELECTION",
                "DF_GM_ELECTION",
                "FAMILY_COUNCIL",
                "EX_OFFICIO_PLACET",
                "STATUTE_CHANGE",
                "RITE_CHANGE",
                "ORIENT_CHANGE",
                "DISTINCTIVE_TITLE_CHANGE",
                "LODGE_MERGER",
                name="session_subtype_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("AGENDADA", "EM_ANDAMENTO", "REALIZADA", "ENCERRADA", "CANCELADA", name="session_status_enum"),
            nullable=False,
        ),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("administration_id", sa.Integer(), nullable=True),
        sa.Column("temporary_role_assignments", sa.JSON(), nullable=True),
        sa.Column("agenda", sa.Text(), nullable=True),
        sa.Column("sent_expedients", sa.Text(), nullable=True),
        sa.Column("received_expedients", sa.Text(), nullable=True),
        sa.Column("study_director_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["administration_id"],
            ["administrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_director_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_masonic_sessions_id"), "masonic_sessions", ["id"], unique=False)
    op.create_table(
        "notices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("type", sa.Enum("Aviso", "Notícia", name="notice_type_enum"), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("publication_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notices_id"), "notices", ["id"], unique=False)
    op.create_index(op.f("ix_notices_lodge_id"), "notices", ["lodge_id"], unique=False)
    op.create_table(
        "role_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("administration_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("end_date IS NULL OR end_date >= start_date", name="chk_role_history_dates"),
        sa.ForeignKeyConstraint(
            ["administration_id"],
            ["administrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_history_id"), "role_history", ["id"], unique=False)
    op.create_table(
        "webmasters_roles",
        sa.Column("webmaster_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["webmaster_id"],
            ["webmasters.id"],
        ),
        sa.PrimaryKeyConstraint("webmaster_id", "role_id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=True),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=True),
        sa.Column("upload_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_by_member_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["masonic_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_document_type"), "documents", ["document_type"], unique=False)
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    op.create_index(op.f("ix_documents_lodge_id"), "documents", ["lodge_id"], unique=False)
    op.create_index(op.f("ix_documents_session_id"), "documents", ["session_id"], unique=False)
    op.create_table(
        "session_attendances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("visitor_id", sa.Integer(), nullable=True),
        sa.Column("attendance_status", sa.String(length=50), nullable=False),
        sa.Column("check_in_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "check_in_method", sa.Enum("MANUAL", "QR_CODE", "APP_VISITOR", name="check_in_method_enum"), nullable=True
        ),
        sa.Column("check_in_latitude", sa.Float(), nullable=True),
        sa.Column("check_in_longitude", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["masonic_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visitor_id"],
            ["visitors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_attendances_id"), "session_attendances", ["id"], unique=False)
    op.create_table(
        "visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("visit_date", sa.Date(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("home_lodge_id", sa.Integer(), nullable=False),
        sa.Column("visited_lodge_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["home_lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["masonic_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visited_lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "session_id", name="_member_session_visit_uc"),
    )
    op.create_index(op.f("ix_visits_id"), "visits", ["id"], unique=False)
    op.create_index(op.f("ix_visits_visit_date"), "visits", ["visit_date"], unique=False)
    op.create_table(
        "document_signatures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("signature_hash", sa.String(length=64), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("signed_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signed_by_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id"),
    )
    op.create_index(op.f("ix_document_signatures_id"), "document_signatures", ["id"], unique=False)
    op.create_index(
        op.f("ix_document_signatures_signature_hash"), "document_signatures", ["signature_hash"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_signatures_signature_hash"), table_name="document_signatures")
    op.drop_index(op.f("ix_document_signatures_id"), table_name="document_signatures")
    op.drop_table("document_signatures")
    op.drop_index(op.f("ix_visits_visit_date"), table_name="visits")
    op.drop_index(op.f("ix_visits_id"), table_name="visits")
    op.drop_table("visits")
    op.drop_index(op.f("ix_session_attendances_id"), table_name="session_attendances")
    op.drop_table("session_attendances")
    op.drop_index(op.f("ix_documents_session_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_lodge_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_document_type"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("webmasters_roles")
    op.drop_index(op.f("ix_role_history_id"), table_name="role_history")
    op.drop_table("role_history")
    op.drop_index(op.f("ix_notices_lodge_id"), table_name="notices")
    op.drop_index(op.f("ix_notices_id"), table_name="notices")
    op.drop_table("notices")
    op.drop_index(op.f("ix_masonic_sessions_id"), table_name="masonic_sessions")
    op.drop_table("masonic_sessions")
    op.drop_index(op.f("ix_loans_id"), table_name="loans")
    op.drop_table("loans")
    op.drop_index(op.f("ix_financial_transactions_member_id"), table_name="financial_transactions")
    op.drop_index(op.f("ix_financial_transactions_lodge_id"), table_name="financial_transactions")
    op.drop_index(op.f("ix_financial_transactions_id"), table_name="financial_transactions")
    op.drop_index(op.f("ix_financial_transactions_category_id"), table_name="financial_transactions")
    op.drop_table("financial_transactions")
    op.drop_index(op.f("ix_events_lodge_id"), table_name="events")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_committee_members_id"), table_name="committee_members")
    op.drop_table("committee_members")
    op.drop_index(op.f("ix_classified_photos_id"), table_name="classified_photos")
    op.drop_table("classified_photos")
    op.drop_index(op.f("ix_annual_budgets_lodge_id"), table_name="annual_budgets")
    op.drop_index(op.f("ix_annual_budgets_id"), table_name="annual_budgets")
    op.drop_index(op.f("ix_annual_budgets_category_id"), table_name="annual_budgets")
    op.drop_table("annual_budgets")
    op.drop_index(op.f("ix_webmasters_id"), table_name="webmasters")
    op.drop_table("webmasters")
    op.drop_index(op.f("ix_waitlists_id"), table_name="waitlists")
    op.drop_table("waitlists")
    op.drop_index(op.f("ix_publications_id"), table_name="publications")
    op.drop_table("publications")
    op.drop_index(op.f("ix_member_permission_exceptions_id"), table_name="member_permission_exceptions")
    op.drop_table("member_permission_exceptions")
    op.drop_index(op.f("ix_member_lodge_associations_id"), table_name="member_lodge_associations")
    op.drop_table("member_lodge_associations")
    op.drop_index(op.f("ix_lodge_financial_configs_lodge_id"), table_name="lodge_financial_configs")
    op.drop_index(op.f("ix_lodge_financial_configs_id"), table_name="lodge_financial_configs")
    op.drop_table("lodge_financial_configs")
    op.drop_index(op.f("ix_library_items_lodge_id"), table_name="library_items")
    op.drop_index(op.f("ix_library_items_id"), table_name="library_items")
    op.drop_table("library_items")
    op.drop_index(op.f("ix_financial_categories_lodge_id"), table_name="financial_categories")
    op.drop_index(op.f("ix_financial_categories_id"), table_name="financial_categories")
    op.drop_table("financial_categories")
    op.drop_index(op.f("ix_dining_scales_lodge_id"), table_name="dining_scales")
    op.drop_index(op.f("ix_dining_scales_id"), table_name="dining_scales")
    op.drop_table("dining_scales")
    op.drop_index(op.f("ix_committees_id"), table_name="committees")
    op.drop_table("committees")
    op.drop_index(op.f("ix_classifieds_lodge_id"), table_name="classifieds")
    op.drop_index(op.f("ix_classifieds_id"), table_name="classifieds")
    op.drop_table("classifieds")
    op.drop_index(op.f("ix_calendars_lodge_id"), table_name="calendars")
    op.drop_index(op.f("ix_calendars_id"), table_name="calendars")
    op.drop_table("calendars")
    op.drop_index(op.f("ix_administrative_processes_id"), table_name="administrative_processes")
    op.drop_table("administrative_processes")
    op.drop_index(op.f("ix_administrations_lodge_id"), table_name="administrations")
    op.drop_index(op.f("ix_administrations_id"), table_name="administrations")
    op.drop_table("administrations")
    op.drop_table("roles_permissions")
    op.drop_table("obediences_roles_association")
    op.drop_index(op.f("ix_member_obedience_associations_id"), table_name="member_obedience_associations")
    op.drop_table("member_obedience_associations")
    op.drop_index(op.f("ix_lodges_lodge_code"), table_name="lodges")
    op.drop_index(op.f("ix_lodges_id"), table_name="lodges")
    op.drop_table("lodges")
    op.drop_index(op.f("ix_family_members_id"), table_name="family_members")
    op.drop_table("family_members")
    op.drop_index(op.f("ix_decorations_id"), table_name="decorations")
    op.drop_table("decorations")
    op.drop_index(op.f("ix_visitors_id"), table_name="visitors")
    op.drop_index(op.f("ix_visitors_global_visitor_id"), table_name="visitors")
    op.drop_index(op.f("ix_visitors_cim"), table_name="visitors")
    op.drop_table("visitors")
    op.drop_index(op.f("ix_super_admins_username"), table_name="super_admins")
    op.drop_index(op.f("ix_super_admins_id"), table_name="super_admins")
    op.drop_index(op.f("ix_super_admins_email"), table_name="super_admins")
    op.drop_table("super_admins")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_obediences_id"), table_name="obediences")
    op.drop_table("obediences")
    op.drop_index(op.f("ix_members_id"), table_name="members")
    op.drop_index(op.f("ix_members_email"), table_name="members")
    op.drop_index(op.f("ix_members_cpf"), table_name="members")
    op.drop_index(op.f("ix_members_cim"), table_name="members")
    op.drop_table("members")
    op.drop_index(op.f("ix_document_templates_id"), table_name="document_templates")
    op.drop_table("document_templates")
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.drop_index(op.f("ix_books_id"), table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
