'''create_committees_tables

Revision ID: d41be11138e3
Revises: 1bfe2df6f103
Create Date: 2025-12-07 10:57:51.816253

'''
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd41be11138e3'
down_revision = '1bfe2df6f103'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('committee_type', sa.Enum('PERMANENT', 'TEMPORARY', name='committee_type_enum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('president_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.ForeignKeyConstraint(['president_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committees_id'), 'committees', ['id'], unique=False)
    op.create_table('committee_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_members_id'), 'committee_members', ['id'], unique=False)
    op.alter_column('family_members', 'relationship_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Enum('Esposa', 'Filho', 'Filha', name='relationship_type_enum'),
               existing_nullable=False)
    op.alter_column('lodges', 'rite',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Enum('Rito Escocês Antigo e Aceito', 'Rito York', 'Rito Schroder', 'Rito Brasileiro', 'Rito Moderno', 'Rito Adonhiramita', 'Rito Escocês Retificado', name='riteenum'),
               existing_nullable=True)
    op.alter_column('member_lodge_associations', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Enum('Ativo', 'Inativo', 'Desativado', name='memberstatusenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Ativo'"))
    op.alter_column('member_lodge_associations', 'member_class',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Enum('Regular', 'Irregular', 'Emérito', 'Remido', 'Honorário', name='memberclassenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Regular'"))
    op.alter_column('member_permission_exceptions', 'exception_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Enum('Concedida', 'Revogada', name='exceptiontypeenum'),
               existing_nullable=False)
    op.alter_column('members', 'degree',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Enum('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='degree_enum'),
               existing_nullable=True)
    op.alter_column('members', 'registration_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Enum('Pendente', 'Aprovado', 'Rejeitado', name='registration_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Pendente'"))
    op.alter_column('obediences', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Enum('Federal', 'Estadual', name='obediencetypeenum'),
               existing_nullable=False)
    op.alter_column('session_attendances', 'check_in_method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('MANUAL', 'QR_CODE', 'APP_VISITOR', name='check_in_method_enum'),
               existing_nullable=True)
    op.alter_column('visitors', 'degree',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Enum('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='visitor_degree_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'degree',
               existing_type=sa.Enum('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='visitor_degree_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('session_attendances', 'check_in_method',
               existing_type=sa.Enum('MANUAL', 'QR_CODE', 'APP_VISITOR', name='check_in_method_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
    op.alter_column('obediences', 'type',
               existing_type=sa.Enum('Federal', 'Estadual', name='obediencetypeenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('members', 'registration_status',
               existing_type=sa.Enum('Pendente', 'Aprovado', 'Rejeitado', name='registration_status_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'Pendente'"))
    op.alter_column('members', 'degree',
               existing_type=sa.Enum('Aprendiz', 'Companheiro', 'Mestre', 'Mestre Instalado', name='degree_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('member_permission_exceptions', 'exception_type',
               existing_type=sa.Enum('Concedida', 'Revogada', name='exceptiontypeenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('member_lodge_associations', 'member_class',
               existing_type=sa.Enum('Regular', 'Irregular', 'Emérito', 'Remido', 'Honorário', name='memberclassenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'Regular'"))
    op.alter_column('member_lodge_associations', 'status',
               existing_type=sa.Enum('Ativo', 'Inativo', 'Desativado', name='memberstatusenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'Ativo'"))
    op.alter_column('lodges', 'rite',
               existing_type=sa.Enum('Rito Escocês Antigo e Aceito', 'Rito York', 'Rito Schroder', 'Rito Brasileiro', 'Rito Moderno', 'Rito Adonhiramita', 'Rito Escocês Retificado', name='riteenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('family_members', 'relationship_type',
               existing_type=sa.Enum('Esposa', 'Filho', 'Filha', name='relationship_type_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_committee_members_id'), table_name='committee_members')
    op.drop_table('committee_members')
    op.drop_index(op.f('ix_committees_id'), table_name='committees')
    op.drop_table('committees')
    # ### end Alembic commands ###
