"""add guests_count to session_attendance

Revision ID: d4239ef24fb7
Revises: c24f46e815ad
Create Date: 2026-06-30 20:16:57.061337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4239ef24fb7'
down_revision: Union[str, Sequence[str], None] = 'c24f46e815ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_attendances', sa.Column('guests_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_attendances', 'guests_count')
    # ### end Alembic commands ###
