"""Add visitor trust level, checkin windows and audit logs

Revision ID: d47ccfac272d
Revises: a0dff2075963
Create Date: 2026-06-18 11:35:32.934722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd47ccfac272d'
down_revision: Union[str, Sequence[str], None] = 'a0dff2075963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lodge_creation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False, comment='Chanceler que solicitou'),
    sa.Column('requested_lodge_name', sa.String(length=255), nullable=False),
    sa.Column('requested_lodge_number', sa.String(length=50), nullable=True),
    sa.Column('requested_obedience', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'CRIADA', 'REJEITADA', name='lodge_creation_status_enum'), nullable=False),
    sa.Column('resolved_lodge_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['resolved_lodge_id'], ['lodges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lodge_creation_requests_id'), 'lodge_creation_requests', ['id'], unique=False)
    op.create_table('attendance_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('webmaster_id', sa.Integer(), nullable=False),
    sa.Column('target_member_id', sa.Integer(), nullable=True),
    sa.Column('target_visitor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['masonic_sessions.id'], ),
    sa.ForeignKeyConstraint(['target_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['target_visitor_id'], ['visitors.id'], ),
    sa.ForeignKeyConstraint(['webmaster_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_audit_logs_id'), 'attendance_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_audit_logs_session_id'), 'attendance_audit_logs', ['session_id'], unique=False)
    op.add_column('lodges', sa.Column('checkin_window_start_minutes', sa.Integer(), server_default='120', nullable=False, comment='Minutos antes do início para abrir check-in'))
    op.add_column('lodges', sa.Column('checkin_window_end_minutes', sa.Integer(), server_default='120', nullable=False, comment='Minutos depois do início para fechar check-in'))
    trust_level_enum = postgresql.ENUM('Verificado', 'Certificado', name='visitor_trust_level_enum'); trust_level_enum.create(op.get_bind()); op.add_column('visitors', sa.Column('trust_level', sa.Enum('Verificado', 'Certificado', name='visitor_trust_level_enum'), server_default='Verificado', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitors', 'trust_level'); trust_level_enum = postgresql.ENUM('Verificado', 'Certificado', name='visitor_trust_level_enum'); trust_level_enum.drop(op.get_bind())
    op.drop_column('lodges', 'checkin_window_end_minutes')
    op.drop_column('lodges', 'checkin_window_start_minutes')
    op.drop_index(op.f('ix_attendance_audit_logs_session_id'), table_name='attendance_audit_logs')
    op.drop_index(op.f('ix_attendance_audit_logs_id'), table_name='attendance_audit_logs')
    op.drop_table('attendance_audit_logs')
    op.drop_index(op.f('ix_lodge_creation_requests_id'), table_name='lodge_creation_requests')
    op.drop_table('lodge_creation_requests')
    # ### end Alembic commands ###
