'''Add session agenda and expedients

Revision ID: daf69e04105e
Revises: 866540a09111
Create Date: 2025-12-01 18:34:04.928729

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf69e04105e'
down_revision = '866540a09111'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masonic_sessions', sa.Column('agenda', sa.Text(), nullable=True))
    op.add_column('masonic_sessions', sa.Column('sent_expedients', sa.Text(), nullable=True))
    op.add_column('masonic_sessions', sa.Column('received_expedients', sa.Text(), nullable=True))
    op.add_column('masonic_sessions', sa.Column('study_director_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'masonic_sessions', 'members', ['study_director_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'masonic_sessions', type_='foreignkey')
    op.drop_column('masonic_sessions', 'study_director_id')
    op.drop_column('masonic_sessions', 'received_expedients')
    op.drop_column('masonic_sessions', 'sent_expedients')
    op.drop_column('masonic_sessions', 'agenda')
    # ### end Alembic commands ###
