"""Add EntityMessage and MessageAttachment models

Revision ID: dd92e1e4045b
Revises: 16938d1da1f6
Create Date: 2026-06-13 11:07:46.241855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd92e1e4045b'
down_revision: Union[str, Sequence[str], None] = '16938d1da1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_obedience_id', sa.Integer(), nullable=True),
    sa.Column('sender_lodge_id', sa.Integer(), nullable=True),
    sa.Column('recipient_obedience_id', sa.Integer(), nullable=True),
    sa.Column('recipient_lodge_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_lodge_id'], ['lodges.id'], ),
    sa.ForeignKeyConstraint(['recipient_obedience_id'], ['obediences.id'], ),
    sa.ForeignKeyConstraint(['sender_lodge_id'], ['lodges.id'], ),
    sa.ForeignKeyConstraint(['sender_obedience_id'], ['obediences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_messages_id'), 'entity_messages', ['id'], unique=False)
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['entity_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_attachments_id'), 'message_attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_attachments_id'), table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index(op.f('ix_entity_messages_id'), table_name='entity_messages')
    op.drop_table('entity_messages')
    # ### end Alembic commands ###
