"""Make Lodge optional fields nullable

Revision ID: e00264862a7b
Revises: c6b01ca9c3f4
Create Date: 2025-11-26 17:26:04.577027

"""

# revision identifiers, used by Alembic.
revision = "e00264862a7b"
down_revision = "c6b01ca9c3f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
