'''Update Lodge model: remove obedience_name and use RiteEnum for rite

Revision ID: e3bd604a1c77
Revises: 45d98617120e
Create Date: 2025-11-20 09:18:43.784505

'''
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'e3bd604a1c77'
down_revision = '45d98617120e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lodges', 'rite',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('REAA', 'YORK', 'SCHRODER', 'BRAZILIAN', 'MODERN', name='riteenum'),
               existing_nullable=True)
    op.drop_column('lodges', 'obedience_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('obedience_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.alter_column('lodges', 'rite',
               existing_type=sa.Enum('REAA', 'YORK', 'SCHRODER', 'BRAZILIAN', 'MODERN', name='riteenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
