"""feat: Adicionar modelos para Calendário, Eventos, Transações Financeiras e Documentos com multitenancy.

Revision ID: e43494c225e1
Revises: e3bd604a1c77
Create Date: 2025-11-21 09:56:18.626171

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e43494c225e1"
down_revision = "e3bd604a1c77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calendars_id"), "calendars", ["id"], unique=False)
    op.create_index(op.f("ix_calendars_lodge_id"), "calendars", ["lodge_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=True),
        sa.Column("upload_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_by_member_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    op.create_index(op.f("ix_documents_lodge_id"), "documents", ["lodge_id"], unique=False)
    op.create_table(
        "financial_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transaction_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_financial_transactions_id"), "financial_transactions", ["id"], unique=False)
    op.create_index(op.f("ix_financial_transactions_lodge_id"), "financial_transactions", ["lodge_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("lodge_id", sa.Integer(), nullable=False),
        sa.Column("calendar_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["calendars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodge_id"],
            ["lodges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_index(op.f("ix_events_lodge_id"), "events", ["lodge_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_lodge_id"), table_name="events")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_financial_transactions_lodge_id"), table_name="financial_transactions")
    op.drop_index(op.f("ix_financial_transactions_id"), table_name="financial_transactions")
    op.drop_table("financial_transactions")
    op.drop_index(op.f("ix_documents_lodge_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_calendars_lodge_id"), table_name="calendars")
    op.drop_index(op.f("ix_calendars_id"), table_name="calendars")
    op.drop_table("calendars")
    # ### end Alembic commands ###
