"""add whatsapp_notifications_enabled to lodge

Revision ID: e7586c88fbbc
Revises: d4239ef24fb7
Create Date: 2026-06-30 20:25:03.749141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7586c88fbbc'
down_revision: Union[str, Sequence[str], None] = 'd4239ef24fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodges', sa.Column('whatsapp_notifications_enabled', sa.Boolean(), server_default='true', nullable=False, comment='Habilita/desabilita envios automáticos para o WhatsApp (Bumps/Aniversários)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodges', 'whatsapp_notifications_enabled')
    # ### end Alembic commands ###
