"""split decorations remarks into lodge and registry

Revision ID: e8ec7d414db2
Revises: 7fc2c4e223fd
Create Date: 2026-07-27 10:38:02.580531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ec7d414db2'
down_revision: Union[str, Sequence[str], None] = '7fc2c4e223fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decorations', sa.Column('lodge', sa.String(length=255), nullable=True))
    op.add_column('decorations', sa.Column('registry', sa.String(length=255), nullable=True))
    op.drop_column('decorations', 'remarks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decorations', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('decorations', 'registry')
    op.drop_column('decorations', 'lodge')
    # ### end Alembic commands ###
