"""make_cashless_multitenant

Revision ID: ec900aa6b3a6
Revises: 250665656a1f
Create Date: 2026-06-29 09:59:53.405711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec900aa6b3a6'
down_revision: Union[str, Sequence[str], None] = '250665656a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashless_orders', sa.Column('lodge_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_cashless_orders_lodge_id'), 'cashless_orders', ['lodge_id'], unique=False)
    op.create_foreign_key(None, 'cashless_orders', 'lodges', ['lodge_id'], ['id'])
    op.add_column('cashless_products', sa.Column('lodge_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_cashless_products_lodge_id'), 'cashless_products', ['lodge_id'], unique=False)
    op.create_foreign_key(None, 'cashless_products', 'lodges', ['lodge_id'], ['id'])
    op.add_column('cashless_stock_movements', sa.Column('lodge_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_cashless_stock_movements_lodge_id'), 'cashless_stock_movements', ['lodge_id'], unique=False)
    op.create_foreign_key(None, 'cashless_stock_movements', 'lodges', ['lodge_id'], ['id'])
    op.add_column('cashless_wallet_transactions', sa.Column('lodge_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_cashless_wallet_transactions_lodge_id'), 'cashless_wallet_transactions', ['lodge_id'], unique=False)
    op.create_foreign_key(None, 'cashless_wallet_transactions', 'lodges', ['lodge_id'], ['id'])
    op.add_column('cashless_wallets', sa.Column('lodge_id', sa.Integer(), nullable=False, server_default='1'))
    op.drop_constraint(op.f('cashless_wallets_cashless_user_id_key'), 'cashless_wallets', type_='unique')
    op.create_index(op.f('ix_cashless_wallets_lodge_id'), 'cashless_wallets', ['lodge_id'], unique=False)
    op.create_unique_constraint('uq_cashless_user_lodge_wallet', 'cashless_wallets', ['cashless_user_id', 'lodge_id'])
    op.create_foreign_key(None, 'cashless_wallets', 'lodges', ['lodge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cashless_wallets', type_='foreignkey')
    op.drop_constraint('uq_cashless_user_lodge_wallet', 'cashless_wallets', type_='unique')
    op.drop_index(op.f('ix_cashless_wallets_lodge_id'), table_name='cashless_wallets')
    op.create_unique_constraint(op.f('cashless_wallets_cashless_user_id_key'), 'cashless_wallets', ['cashless_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('cashless_wallets', 'lodge_id')
    op.drop_constraint(None, 'cashless_wallet_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_cashless_wallet_transactions_lodge_id'), table_name='cashless_wallet_transactions')
    op.drop_column('cashless_wallet_transactions', 'lodge_id')
    op.drop_constraint(None, 'cashless_stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_cashless_stock_movements_lodge_id'), table_name='cashless_stock_movements')
    op.drop_column('cashless_stock_movements', 'lodge_id')
    op.drop_constraint(None, 'cashless_products', type_='foreignkey')
    op.drop_index(op.f('ix_cashless_products_lodge_id'), table_name='cashless_products')
    op.drop_column('cashless_products', 'lodge_id')
    op.drop_constraint(None, 'cashless_orders', type_='foreignkey')
    op.drop_index(op.f('ix_cashless_orders_lodge_id'), table_name='cashless_orders')
    op.drop_column('cashless_orders', 'lodge_id')
    # ### end Alembic commands ###
