'''translate_enums_to_portuguese

Revision ID: f0c423b2f71e
Revises: 3472cd8ec2b7
Create Date: 2025-11-25 07:41:45.788495

'''
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0c423b2f71e'
down_revision = '3472cd8ec2b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lodges', 'session_day',
               existing_type=mysql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('Domingo', 'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado', name='session_day_enum'),
               existing_nullable=True)
    op.alter_column('lodges', 'periodicity',
               existing_type=mysql.ENUM('Weekly', 'Biweekly', 'Monthly', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('Semanal', 'Quinzenal', 'Mensal', name='periodicity_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lodges', 'periodicity',
               existing_type=sa.Enum('Semanal', 'Quinzenal', 'Mensal', name='periodicity_enum'),
               type_=mysql.ENUM('Weekly', 'Biweekly', 'Monthly', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('lodges', 'session_day',
               existing_type=sa.Enum('Domingo', 'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado', name='session_day_enum'),
               type_=mysql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###
