"""add_absence_justifications

Revision ID: fc753476b07d
Revises: d47ccfac272d
Create Date: 2026-06-18 13:55:25.564262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc753476b07d'
down_revision: Union[str, Sequence[str], None] = 'd47ccfac272d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_justifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('justification_text', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('Pendente', 'Aprovado', 'Rejeitado', name='absence_status_enum'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['masonic_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'member_id', name='_member_session_absence_uc')
    )
    op.create_index(op.f('ix_absence_justifications_id'), 'absence_justifications', ['id'], unique=False)
    op.create_index(op.f('ix_absence_justifications_member_id'), 'absence_justifications', ['member_id'], unique=False)
    op.create_index(op.f('ix_absence_justifications_session_id'), 'absence_justifications', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_absence_justifications_session_id'), table_name='absence_justifications')
    op.drop_index(op.f('ix_absence_justifications_member_id'), table_name='absence_justifications')
    op.drop_index(op.f('ix_absence_justifications_id'), table_name='absence_justifications')
    op.drop_table('absence_justifications')
    # ### end Alembic commands ###
