'''ensure_administration_id_in_role_history

Revision ID: fd6bd6dae1c8
Revises: 1f4ea8e6f22f
Create Date: 2025-12-12 09:56:53.515664

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6bd6dae1c8'
down_revision = '1f4ea8e6f22f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_history', sa.Column('administration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role_history', 'administrations', ['administration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_history', type_='foreignkey')
    op.drop_column('role_history', 'administration_id')
    # ### end Alembic commands ###
