'''refactor_role_history

Revision ID: fe6c2cf21501
Revises: 6ff4267b1524
Create Date: 2025-11-27 14:09:34.015763

'''
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe6c2cf21501'
down_revision = '6ff4267b1524'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('member_lodge_associations_ibfk_3'), 'member_lodge_associations', type_='foreignkey')
    op.drop_column('member_lodge_associations', 'role_id')
    op.add_column('role_history', sa.Column('lodge_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'role_history', 'lodges', ['lodge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_history', type_='foreignkey')
    op.drop_column('role_history', 'lodge_id')
    op.add_column('member_lodge_associations', sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('member_lodge_associations_ibfk_3'), 'member_lodge_associations', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
