'''feat: Evoluir modelos para gestão de sessões e QR code

Revision ID: ff32fa4e7a71
Revises: e43494c225e1
Create Date: 2025-11-21 10:24:50.943169

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff32fa4e7a71'
down_revision = 'e43494c225e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'masonic_sessions', ['session_id'], ['id'])
    op.add_column('masonic_sessions', sa.Column('status', sa.Enum('AGENDADA', 'EM_ANDAMENTO', 'REALIZADA', 'CANCELADA', name='session_status_enum'), nullable=False))
    op.add_column('session_attendances', sa.Column('check_in_method', sa.Enum('MANUAL', 'QR_CODE', name='check_in_method_enum'), nullable=True))
    op.add_column('session_attendances', sa.Column('check_in_latitude', sa.Float(), nullable=True))
    op.add_column('session_attendances', sa.Column('check_in_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_attendances', 'check_in_longitude')
    op.drop_column('session_attendances', 'check_in_latitude')
    op.drop_column('session_attendances', 'check_in_method')
    op.drop_column('masonic_sessions', 'status')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_column('documents', 'session_id')
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
